### ISSUE TITLE
[Issue] With Mexican and Arg Numbers +52  

### ISSUE THREAD

**Issue by aldoximple** [codigoencasa/bot-whatsapp#1004]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@bot-whatsapp/provider@0.1.38` for the project I'm working on.

When I was using Mexican phone number with meta provider a '1' character to the body.to property. So this cause an invalid number.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@bot-whatsapp/provider/lib/meta/index.cjs b/node_modules/@bot-whatsapp/provider/lib/meta/index.cjs
index 5bbdeb3..e8d8b86 100644
--- a/node_modules/@bot-whatsapp/provider/lib/meta/index.cjs
+++ b/node_modules/@bot-whatsapp/provider/lib/meta/index.cjs
@@ -579,6 +579,13 @@ class MetaProvider extends ProviderClass {
      * @return {Object} The response data from the API.
      */
     async sendMessageToApi(body) {
+        if (body.to.slice(0, 2) == '52') {
+            if (body.to.length > 12) {
+                let lada = body.to.slice(0, 2)
+                let number = body.to.slice(3, 14)
+                body.to = lada+number
+            }
+        }
         try {
             const response = await axios.post(`${URL$1}/${this.version}/${this.numberId}/messages`, body, {
                 headers: {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by rodrimarchese** [comment]
Fixed en https://github.com/codigoencasa/bot-whatsapp/pull/1044
