### ISSUE TITLE
[🐛]Se desvincula la sesion de WP

### ISSUE THREAD

**Issue by andrescamilo1415** [codigoencasa/bot-whatsapp#1006]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

DialogFlow

### Describe tu problema

Se despliega un chatbot basico para pruebas en una maquina aws ec t2.micro, ubuntu de 1g de ram y 1 vcore.
de despliega usando pm2 sin prblemas y en cualquier momento de desvincula la sesion de whatsapp (baileys) (bd: mock) (es para pruebas de concepto).
El servidor es pequeño, pero SOLO tiene corriendo ese proceso, le quedan como 700 Mb de memoria libre.
en pruebas se dejo mucho tiempo y nunca se perdio la sesion de WP

### Información Adicional

![Screenshot 2024-02-27](https://github.com/codigoencasa/bot-whatsapp/assets/69878559/15235d30-0706-4d50-8892-b3d8c4a5f623)

**Comment by ozzyoss77** [comment]
@andrescamilo1415 el problema esta en que no hay persistencia de datos de la sesión, según veo en la consola se reinicia el bot y por lo tanto hay que volverlo a vincular, te recomiendo pasar a docker y montar un volumen que apunte a /app/bot_sessions para mantener persistencia de credenciales en caso de reinicio.

Cierro la issue.
