### ISSUE TITLE
Problemas con el uso de {capture:true} en un addAction[🐛]

### ISSUE THREAD

**Issue by mpgigat** [codigoencasa/bot-whatsapp#1011]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

-Al llamar un flujo con gotoFlow, que contenga {capture:ture} reinicia el flujo
-usando mongodb como database general el inconveniente
-Usando mock funciona correctamente

ejemplo de flujo

```
const flowBuy = addKeyword(EVENTS.ACTION)
    .addAction(async(_,{flowDynamic})=>{
       return await flowDynamic([{ body: "cual es tu nombre" }]);
    })
    .addAction({capture:true},async(ctx,{flowDynamic})=>{
        return await flowDynamic([{ body: `te llamas ${ctx.body}`}]);
    })
```
Al econtrar un {capture:true}, se reincia el flujo, es decir vuelve al flujo inicial.

link repo ejemplo:  https://github.com/mpgigat/chatbot

### Reproducir error

https://youtu.be/jIe5hCtvlF4

**Comment by ozzyoss77** [comment]
@mpgigat lo que logro observar es una falla en la logica que maneja el bot, si puedes proporcionar la versión de la lib que estas usando para realizar pruebas mas exhaustivas por favor.

Ejemplo: v.0.1.38

En la versiones probadas no ocurre el error.

**Comment by mpgigat** [comment]
hola, lo he probado con la v.0.1.38

**Comment by leifermendez** [comment]
Si, entiendo solo por.descartar prueba con addAnwser en lugar de addAction

**Comment by jaimecalderon19** [comment]
ya solucionaron este error?

**Comment by leifermendez** [comment]
> ya solucionaron este error?

Si pero está en la versión nueva que sacamos hace un par de días pasaré por builderbot.app

**Comment by jaimecalderon19** [comment]
@leifermendez  acabe de actualizar mis dependencia a lastest y no me funciona el capture, si cabio el db a Memory funciona correctamente.
![image](https://github.com/codigoencasa/bot-whatsapp/assets/156539649/dbb05993-15e9-457e-8f04-2102a68aff03)

**Comment by leifermendez** [comment]
> @leifermendez acabe de actualizar mis dependencia a lastest y no me funciona el capture, si cabio el db a Memory funciona correctamente. ![image](https://private-user-images.githubusercontent.com/156539649/322225493-dbb05993-15e9-457e-8f04-2102a68aff03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMzQ0NjcsIm5iZiI6MTcxMzAzNDE2NywicGF0aCI6Ii8xNTY1Mzk2NDkvMzIyMjI1NDkzLWRiYjA1OTkzLTE1ZTktNDU3ZS04ZjA0LTIxMDJhNjhhZmYwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxM1QxODQ5MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDc0YzQ4NjE2NGQxNDQ3ZjNmMWMwYTQxM2I3ODExYWU1Y2FmOTNkZWQwMDBmZWRiMWNjOTJiMWY4MWUwYzY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lEuIi7somQs3wQaMuxgFA1J0eAG_UWtO_Ex-lU-3TzQ)

Pasate por el discord https://link.codigoencasa.com/DISCORD pero no me refiero a latest me refiero a y usar builderbot.app pasate por la doc
