### ISSUE TITLE
[🐛 Colocar etiqueta/label a chat

### ISSUE THREAD

**Issue by EmenetSistemas** [codigoencasa/bot-whatsapp#1015]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Otro

### Describe tu problema

const abc = await provider.getInstance();
await abc.chatModify({ addChatLabel: { labelId: 1 } }, ctx.key.remoteJid);
                
Intento colocar una etiqueta a un chat, pero no sucede nada (seguramente estoy mal en algo), y para empezar no termino de entender como se debería hacer, no veo esto en la documentación, pero si en el archivo que se encuentra en esta ubicación

\node_modules\@whiskeysockets\baileys\lib\Socket\index.d.ts

Alguien que lo haya realizado y me pueda ayudar con su solución

**Comment by pupimarti** [comment]
hola, sabés como obtener los label de un chat?
