### ISSUE TITLE
[🐛] sendLocation con Baileys

### ISSUE THREAD

**Issue by capidreamliner** [codigoencasa/bot-whatsapp#1025]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Otro

### Describe tu problema

¡Hola! 

En primer lugar, me gustaría agradecer a todos los colaboradores de este proyecto por el increíble trabajo que han hecho.

El motivo por el que les escribo hoy es para hacer notar un problema en la documentación y recibir ayuda para usar sendLocation con Baileys. Este es el ejemplo que figura en la página del proveedor:

**Baileys:
Enviar ubicación**
```
const flowPrincipal = addKeyword('hola')
    .addAnswer(
        'Aqui va un mensaje',
        { capture: true},
        async (ctx, {provider}) => {
            await provider.sendLocation(ctx.from@s.whatsapp.net, 'audio url')
            // el número de telefono se envía en este formato 12345678901@s.whatsapp.net
        }
    )
```
    
   Como dice "audio url" asumo que debe tratarse de un error.  Agradecería su ayuda para poder implementar esta funcionalidad.
   
   ¡Muchas gracias! Que tengan un excelente día.

**Comment by rodrimarchese** [comment]
quizas te sirve un ejemplo de sendLocation que hizo Jorge Chavarriaga:


https://github.com/jorgechavarriaga/builder_bot_baileys_examples/tree/master/sendLocation

**Comment by EmenetSistemas** [comment]
async ({ from }, { provider }) => {
    const abc = await provider.getInstance();
    return await abc.sendMessage(
        from + '@c.us',
        { location: { degreesLatitude: XX.XXXXXX, degreesLongitude: -XX.XXXXXX } }
    );
}

Tal vez esto te pueda ayudar
