### ISSUE TITLE
[🐬] ¿Como se puede borrar los datos del state?

### ISSUE THREAD

**Issue by jesusmatiz35** [codigoencasa/bot-whatsapp#1026]
### ¿Cual proveedor usaste?

whatsapp-web.js

### ¿Cual base de datos usaste?

mongo

### Conclusion de la prueba

muy buena

### Describe tu caso

Quiero borrar los datos del state cuando termine el flujo conversacional con el endFlow, ¿Como podría hacerlo?

### ¿Quieres que te mencionemos?

www.jesusmatiz.com

**Comment by rodrimarchese** [comment]
Podes agregar esto, antes de endFlow. Lo podes encontrar aca:

<img width="1097" alt="image" src="https://github.com/codigoencasa/bot-whatsapp/assets/32769860/dc08d98a-bb05-433d-8f27-3e287a353918">
 
 https://www.builderbot.app/en/methods#state
