### ISSUE TITLE
Como Escanear QR desde FrontEnd

### ISSUE THREAD

**Issue by Goodfrey** [codigoencasa/bot-whatsapp#103]
Saludos.  Espero se encuentren bien... comunidad... todos sabemos que el bot esta en la capacidad de generar una imagen desde un codigo qr para que se visualice y se escane normalmente. 

Mi pregunta es la siguiente...

Alguno ha podido realizar una conexion Cliente-Servidor para que escanear el Codigo QR en un projecto Front End como laravel, angular, React, 

Es decir... Si quisiera desarrollar el front end en laravel y utilizar el bot realizado en nodejs, es posible escanear dicho codigo QR desde un modal por ejemplo ?

Gracias por la respuesta.

**Comment by leifermendez** [comment]
@aurik3 cuando puedas revisa el discord te deje un mensaje

**Comment by Goodfrey** [comment]
Lo que pasa es que estoy mejor preparado para para el front end con php por eso mi pregunta... Xq se que está librería trabaja del lado del servidor con node y express.

Se que leifer hizo que el servidor mostrará el QR en una ventana diferente....

Yo quiero hacer eso mismo pero que el servidor envié el QR para mostrarlo en un proyecto en Lara el y luego laravel le indique al backend que fue conectado el WhatsApp..


Será posible hacer eso... ?

Gracias por la respuesta

**Comment by Javierfernandez93** [comment]
Monta un socket y emite el QR al cliente (se recibe en base64). O si es para una sesión hazlo con un api rest
