### ISSUE TITLE
[🐛] const version = indexHtml.match(/manifest-([\d\\.]+)\.json/)[1];

### ISSUE THREAD

**Issue by WichyAlonzo** [codigoencasa/bot-whatsapp#1033]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

async persist(indexHtml) {
        // extract version from index (e.g. manifest-2.2206.9.json -> 2.2206.9)
        const version = indexHtml.match(/manifest-([\d\\.]+)\.json/)[1];
        if (!version) return;

        const filePath = path.join(this.path, `${version}.html`);
        fs.mkdirSync(this.path, { recursive: true });
        fs.writeFileSync(filePath, indexHtml);
    }
    
    help me
![image](https://github.com/codigoencasa/bot-whatsapp/assets/67400844/dfc553d9-cbec-459e-baca-a9b23d5d4826)

**Comment by rodrimarchese** [comment]
Ese error estoy casi seguro que es de la libreria de whatsapp web. En un proyecto aparte que la estoy utilizando, me pasa el mismo error.

**Comment by jorgechavarriaga** [comment]
Es un error del proveedor no de la libreria.
