### ISSUE TITLE
[🐬]NETLIFY DEPLOY

### ISSUE THREAD

**Issue by jandermartins** [codigoencasa/bot-whatsapp#1038]
### ¿Cual proveedor usaste?

bailey

### ¿Cual base de datos usaste?

json

### Conclusion de la prueba

muy buena

### Describe tu caso

Para conseguir fazer o deploy no netlify, o bot poderia escrever no terminal o QR Code ao executar o comando npm start para conectar no servidor WhatsApp.

### ¿Logs Importantes?

```shell
ok
```

**Comment by jandermartins** [comment]
Eu tentei fazer algumas modificações mas não consegui. Em tese teria que
fazer o qrcode printar automaticamente no console do netlify durante o
deploy

Att

Jander Martins, Graduando em Ciência da Computação pela Universidade
Federal do Ceará


Em sex., 7 de jun. de 2024 às 20:00, github-actions[bot] <
***@***.***> escreveu:

**Comment by ozzyoss77** [comment]
@jandermartins con nuestra versión de [Builderbot](https://builderbot.vercel.app/en) el tema esta totalemente solucionado porque tienes el qr disponible en un endpoint `http://localhost:3000/`, te invito a revisarlo y pasar por nuestro canal de [Discord](https://discord.com/channels/915193197645402142/970206231849492480)
