### ISSUE TITLE
[🐛] Baileys cunado envian varios multimedia solo cpatura el primero

### ISSUE THREAD

**Issue by leifermendez** [codigoencasa/bot-whatsapp#1051]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

Baileys cunado envian varios multimedia solo cpatura el primero
https://discord.com/channels/915193197645402142/1232388012088754327

**Comment by leifermendez** [comment]
```ts
import { createBot, createProvider, createFlow, addKeyword, utils, EVENTS } from '@builderbot/bot'
import { MemoryDB as Database } from '@builderbot/bot'
import { BaileysProvider as Provider } from '@builderbot/provider-baileys'

const PORT = process.env.PORT ?? 3008

const discordFlow = addKeyword<Provider, Database>(EVENTS.MEDIA).addAction(async (ctx, { provider, flowDynamic }) => {
    const filePath = await provider.saveFile(ctx, { path: `./` })
    await flowDynamic([{ body: `Saved...${filePath}`, delay: 600 }])
})

const main = async () => {
    const adapterFlow = createFlow([discordFlow])

    const adapterProvider = createProvider(Provider)
    const adapterDB = new Database()

    const { httpServer } = await createBot({
        flow: adapterFlow,
        provider: adapterProvider,
        database: adapterDB,
    })

    httpServer(+PORT)
}

main()

```

De esta manera funciona si envias 4 imagenes se dispara el evento 4 veces y guarda

**Comment by vladi965** [comment]
@leifermendez una consulta como guardo una foto con baileys en mi base de datos mysql, estoy usando el chatbot esta version https://bot-whatsapp.netlify.app/ y ya he avanzado el codigo, pero cuando tomo una foto o se sube una foto no se logra guardar la imagen en una carpeta upload y luego guardarse en la base de datos, tendras un ejemplo, Te agradeceria mucho 🙏🙏
