### ISSUE TITLE
Fast Entires[🐛]

### ISSUE THREAD

**Issue by DavidKingV** [codigoencasa/bot-whatsapp#1055]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

Estoy tratando de implementar Fast-Entores, la solución para capturar mensajes enviados dentro de un margen de tiempo y procesarlos como uno solo. Use la función que esta en la documentación pero no funciona.  
![Anotación 2024-04-28 140748](https://github.com/codigoencasa/bot-whatsapp/assets/82010394/4356fddc-289d-40d8-9422-7ef54c046f4d)

Si se envía mas de un mensaje dentro de tiempo establecido (3 segundos) el flow ya no continua y se dirige al flow principal. Pero si solo se envía un mensaje, la función sigue correctamente

**Comment by DavidKingV** [comment]
Alguna actualización?

**Comment by leifermendez** [comment]
Actualizare con la mejoras en la documentación

**Comment by leifermendez** [comment]
Ya se actualizado la documentacion https://www.builderbot.app/en/showcases/fast-entires
