### ISSUE TITLE
Problema con base de datos mysql[🐛]

### ISSUE THREAD

**Issue by DavidKingV** [codigoencasa/bot-whatsapp#1057]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Base de datos

### Describe tu problema

Al usar Mysql como base de datos ocurre este error: Error: Can't add new command when connection is in closed state

Pasa cuando un numero nuevo escribe al bot, al reiniciar el bot y volver a escribirle, ya funciona.

![image](https://github.com/codigoencasa/bot-whatsapp/assets/82010394/16fa56bc-162b-4de1-bf6d-9a339aeaae44)

**Comment by DavidKingV** [comment]
Si a alguien le sirve, parece que se resolvió al actualizar la versión "@builderbot/database-mysql": "^1.1.5", y "@builderbot/bot": "1.1.5", Aunque aun no estoy seguro. Sigo haciendo pruebas

**Comment by leifermendez** [comment]
Creo que esto tiene que ver más con el server de TU MySQL igualmente lo miraré pero dime tu server de MySQL es local o cloud?

**Comment by DewGenial** [comment]
En realidad el error tenia fuente en provider-baileys y fue corregido desde la version 6.7.2 de baileys
