### ISSUE TITLE
[🐛] Problema de instalación.

### ISSUE THREAD

**Issue by joelgpc** [codigoencasa/bot-whatsapp#1061]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Otro

### Describe tu problema

He intentado de todo, llevo 4 horas y no encuentro la solución, me podéis ayudar?
┌  Vamos a crear un  Chatbot  ✨
│
◇  ¿Quieres continuar?
│  Yes
│
◇  ¿Cuál proveedor de whatsapp quieres utilizar?
│  Baileys
│
◇  ¿Cuál base de datos quieres utilizar?
│  Memory
│
◇  Comprobando requerimientos
│
│
◇  Creando proyecto
│
◇  Instrucciones: ───────────────────────────╮
│                                            │
│   cd base-baileys-memory                   │
│   npm install                              │
│   npm start                                │
│                                            │
│     https://bot-whatsapp.netlify.app       │
│                                            │
│  🤖 ¿Problemas? Únete:                     │
│     https://link.codigoencasa.com/DISCORD  │
│                                            │
├────────────────────────────────────────────╯
│
└  Finalizado correctamente!

PS C:\Users\joel_\source\repos\botWhatsapp-1> cd base-baileys-memory                   │
>> │   npm install
Set-Location : No se encuentra ningún parámetro de posición que acepte el argumento '│'.
En línea: 1 Carácter: 1
+ cd base-baileys-memory                   │
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-Location], ParameterBindingException
 
│ : El término '│' no se reconoce como nombre de un cmdlet, función, archivo de script o programa ejecutable. Compruebe si escribió correctamente el nombre o, si incluyó una ruta de acceso, compruebe que dicha ruta es        
correcta e inténtelo de nuevo.
En línea: 2 Carácter: 1
+ │   npm install
+ ~
    + CategoryInfo          : ObjectNotFound: (│:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\Users\joel_\source\repos\botWhatsapp-1> cd base-baileys-memory
>> npm install
npm WARN deprecated phin@2.9.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.      
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 481 packages, and audited 482 packages in 1m

51 packages are looking for funding

15 vulnerabilities (6 moderate, 7 high, 2 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
PS C:\Users\joel_\source\repos\botWhatsapp-1\base-baileys-memory> npm start

> base-bailey-memory@1.0.0 prestart
> npx eslint . --no-ignore

Oops! Something went wrong! :(

ESLint: 8.57.0

ESLint couldn't find the plugin "eslint-plugin-bot-whatsapp".

(The package "eslint-plugin-bot-whatsapp" was not found when loaded as a Node module from the directory "C:\Users\joel_\source\repos\botWhatsapp-1".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install eslint-plugin-bot-whatsapp@latest --save-dev

The plugin "eslint-plugin-bot-whatsapp" was referenced from the config file in "..\.eslintrc.js".

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.

PS C:\Users\joel_\source\repos\botWhatsapp-1\base-baileys-memory> 

![image](https://github.com/codigoencasa/bot-whatsapp/assets/169929351/0ecfd1f0-c24e-4cae-84dd-816be7a1655f)

**Comment by leifermendez** [comment]
Buenas puede ser una versiones de tu Node pero te invito a mirar builderbot.app es lo mismo pero con otro nombre que estamos por temas de marketing

**Comment by joelgpc** [comment]
Me sigue pasando lo mismo.

┌   Let's create a  Chatbot v1.1.5 ✨
│
◇  Do you want to continue?
│  Yes
│
◇  Which WhatsApp provider do you want to use?
│  Baileys
│
◇  Which database do you want to use?
│  Memory
│
◇  Which language do you prefer to use?
│  TypeScript
│
◇  Checking requirements
│
◇  Creating project...
│
◇  Instructions: ────────────────────────────╮
│                                            │
│   cd base-ts-baileys-memory                │
│   npm install                              │
│   npm run dev                              │
│  📄 Documentation:                         │
│     https://builderbot.vercel.app          │
│                                            │
│  🤖 Issues? Join:                          │
│     https://link.codigoencasa.com/DISCORD  │
│                                            │
├────────────────────────────────────────────╯
│
└   Successfully completed! 

PS C:\Users\joel_\source\repos\documentation>  cd base-ts-baileys-memory 

added 372 packages, and audited 373 packages in 54s

┌   Let's create a  Chatbot v1.1.5 ✨
│
◇  Do you want to continue?
│  Yes
│
◇  Which WhatsApp provider do you want to use?
│  Baileys
│
◇  Which database do you want to use?
│  Memory
│
◇  Which language do you prefer to use?
│  TypeScript
│
◇  Checking requirements
│
◇  Creating project...
│
◇  Instructions: ────────────────────────────╮
│                                            │
│   cd base-ts-baileys-memory                │
│   npm install                              │
│   npm run dev                              │
│                                            │
│  📄 Documentation:                         │
│     https://builderbot.vercel.app          │
│  🤖 Issues? Join:                          │
│     https://link.codigoencasa.com/DISCORD  │
│                                            │
├────────────────────────────────────────────╯
│
└   Successfully completed!

PS C:\Users\joel_\source\repos\documentation\base-ts-baileys-memory> cd base-ts-baileys-memory
PS C:\Users\joel_\source\repos\documentation\base-ts-baileys-memory\base-ts-baileys-memory>  npm install

added 372 packages, and audited 373 packages in 16s

81 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS C:\Users\joel_\source\repos\documentation\base-ts-baileys-memory\base-ts-baileys-memory> npm run dev

> base-bailey-json@1.0.0 dev
> npm run lint && nodemon ./src/app.ts


> base-bailey-json@1.0.0 lint
> eslint . --no-ignore


Oops! Something went wrong! :(

ESLint: 8.57.0

ESLint couldn't find the plugin "eslint-plugin-prettier".

(The package "eslint-plugin-prettier" was not found when loaded as a Node module from the directory "C:\Users\joel_\source\repos\documentation".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install eslint-plugin-prettier@latest --save-dev

The plugin "eslint-plugin-prettier" was referenced from the config file in "..\..\.eslintrc.js".

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.

PS C:\Users\joel_\source\repos\documentation\base-ts-baileys-memory\base-ts-baileys-memory> 

![image](https://github.com/codigoencasa/bot-whatsapp/assets/169929351/d4a94356-a948-418c-a903-521c48c2a2fa)

**Comment by leifermendez** [comment]
Veo algo raro en tu proyecto create una carpeta nueva porque lo que envías
que dice base-baily se ve raro

**Comment by joelgpc** [comment]
Voy paso a paso, desde cero. 
![image](https://github.com/codigoencasa/bot-whatsapp/assets/169929351/4ed7fd7a-20e3-4778-b764-37520dbfb080)
Instalación: Creo que se crea un contendor nuevo al instalarlo como puedes observar.
![image](https://github.com/codigoencasa/bot-whatsapp/assets/169929351/508aec1e-cc22-4a68-a23f-1b5498df7874)
Instalación completa al parecer:
![image](https://github.com/codigoencasa/bot-whatsapp/assets/169929351/dca92aec-814b-4c4e-b557-0b491cbd559b)
Otra vez el error:
![image](https://github.com/codigoencasa/bot-whatsapp/assets/169929351/65abb97c-9312-4a49-8099-e6ccc066b49a)

Ayuda por favor!

**Comment by leifermendez** [comment]
Ok perfecto ejecuta ese comando que te sale en el último screenshot donde dice ejecutar

**Comment by leifermendez** [comment]
Si el error persiste únete al grupo de discord https://link.codigoencasa.com/DISCORD por discord es el canal oficial para este tipo de cosas

**Comment by joelgpc** [comment]
Ejecutado.
![image](https://github.com/codigoencasa/bot-whatsapp/assets/169929351/0d782bb3-4a9b-4c3e-b4f9-106e299a0c48)
Mismo error.
![image](https://github.com/codigoencasa/bot-whatsapp/assets/169929351/be6d453b-dc0b-4be3-9fb8-326626b14e08)

Voy al discord porque llevo todo el día en esto :D

**Comment by leifermendez** [comment]
Pero ya va veo que tienes el proyecto metido en otro proyecto de Next

**Comment by leifermendez** [comment]
Ese es el problema créalo como un proyecto solo afuera

**Comment by joelgpc** [comment]
Tampoco me deja entrar en el Discord. 
![Uploading image.png…]()

**Comment by DavidKingV** [comment]
> > Ese es el problema créalo como un proyecto solo afuera
> 
> Perdona mi ignorancia, pero como creo el proyecto solo afuera?

Ya intentaste usandpo pnpm? Yo intentaba con npm  y siempre habia errores. Cambie a pnpm y funciona correctamente.

**Comment by heetin** [comment]
Hola buenas tardes! Tengo el mismo error, como pudiste solucionarlo?

**Comment by leifermendez** [comment]
Puedes usar pnpm
