### ISSUE TITLE
Multiples dispositivos en un mismo servidor

### ISSUE THREAD

**Issue by rubengplatas** [codigoencasa/bot-whatsapp#1062]
### ¿Cual proveedor usaste?

bailey

### ¿Cual base de datos usaste?

memory

### Conclusion de la prueba

tiene errores

### Describe tu caso

Hola, hemos montado dos servidores web con dos puertos distintos en un mismo VPS para poder usar dos líneas de whatsapp distintas. En el dispositivo físico tengo dos whatsapp con dos números de teléfono distintos (uno con whatsapp normal y otro con whatsapp business).
Enlazamos el primer dispositivo correctamente , pero al enlazar el segundo, se desconectan ambos y no funciona. Estamos montándolo con el sistema pm2.
Hemos hecho otra prueba usando dos VPS distintos y así sí funciona, no entendemos qué ocurre para que no funcione en el mismo servidor (con dos puertos distintos). ¿Podríais ayudarme?

Gracias!

**Comment by mastercodelatam** [comment]
¿Imagino que está corriendo en Windows Server al usar PM2, puede dar más detalles de como hace el despliegue?
Adjunte el directorio y los pasos para su despliegue tanto del bot 1 y bot 2.

Recomendación: Usar Docker.
Sospecha: se está desplegando en la misma carpeta y se está borrando la key del dispositivo. Conflicto de directorios.

**Comment by rubengplatas** [comment]
> ¿Imagino que está corriendo en Windows Server al usar PM2, puede dar más detalles de como hace el despliegue? Adjunte el directorio y los pasos para su despliegue tanto del bot 1 y bot 2.
> 
> Recomendación: Usar Docker. Sospecha: se está desplegando en la misma carpeta y se está borrando la key del dispositivo. Conflicto de directorios.

Estamos usando pm2 en Ubuntu. Efectivamente el problema era el despliegue en el mismo directorio, lo hemos duplicado y así sí ha funcionado. Muchas gracias.

**Comment by ozzyoss77** [comment]
@rubengplatas paso a cerrar el tema.
