### ISSUE TITLE
[🐛] No se carga el QR en la página para la vinculación del dispositivo

### ISSUE THREAD

**Issue by AntonioHReyes** [codigoencasa/bot-whatsapp#1063]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Otro

### Describe tu problema

Hice un redeploy de mi proyecto sobre railway y aunque no me esta tronando, ni marca ningún error, la página que muestra el QR no lo esta cargando

Estoy usando Baileys como proveedor

este es mi package.json

```javascript
{
    "name": "base-bailey-mysql",
    "version": "1.0.0",
    "description": "",
    "main": "app.js",
    "scripts": {
        "pre-copy": "cd .. && npm run  copy.lib base-baileys-mysql",
        "start": "node app.js",
        "start:prod": "dotenv -e prod.env node app.js",
        "start:dev": "dotenv -e dev.env node app.js"
    },
    "keywords": [],
    "dependencies": {
        "@bot-whatsapp/bot": "latest",
        "@bot-whatsapp/cli": "latest",
        "@bot-whatsapp/database": "latest",
        "@bot-whatsapp/portal": "latest",
        "@bot-whatsapp/provider": "latest",
        "@whiskeysockets/baileys": "^6.4.0",
        "mysql2": "^2.3.3",
        "wa-sticker-formatter": "4.3.2"
    },
    "author": "",
    "license": "ISC"
}
``` 

![image](https://github.com/codigoencasa/bot-whatsapp/assets/51680520/c38b335e-746e-4116-a3f9-c11eb7584b14)

**Comment by DavidKingV** [comment]
Hola. Asegúrate de que en la configuración de tu proyecto tienes activa la función de Public Networking. Una vez desplegado el proyecto, podrás abrir una url donde estará el QRcuando en la terminar aparezca que esta listo para ser escaneado

. 
![image](https://github.com/codigoencasa/bot-whatsapp/assets/82010394/da353b22-5033-4482-84a6-7d449ed1defd)

**Comment by AntonioHReyes** [comment]
Hola @DavidKingV si la tengo publica, de ahi tome la captura que puse en la descripción del issue y los logs ya me indican que capture el QR pero este no se muestra en esa página.

![image](https://github.com/codigoencasa/bot-whatsapp/assets/51680520/d531dc8c-aa0c-4ce0-b35d-af9d5be10db9)

![image](https://github.com/codigoencasa/bot-whatsapp/assets/51680520/cb86233e-0966-4cb3-bafc-0cb92e14e991)

**Comment by DavidKingV** [comment]
Entiendo, probablemente es un error de la librería. Ahora que veo estas usando la versión "anterior" Ya que yo uso BuilderBot en lugar de bot-whatsapp. Te recomendaría cambiar a la nueva librería.

**Comment by AntonioHReyes** [comment]
@DavidKingV Oki jajaja oh shit here we go again, con una migración. muchas gracias, tocara re hacer el proyecto 😭.

**Comment by AntonioHReyes** [comment]
Cerro el issue, actualize la versión y ajuste el código y funciono de nuevo.

El flowDynamic esta fallando con el addAnswer en la última version, así que toco ajustarlo dentro de un addAction
