### ISSUE TITLE
Bug al intentar enviar un Gif en el flow Welcome[🐛]

### ISSUE THREAD

**Issue by jalejandro0211** [codigoencasa/bot-whatsapp#1065]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

Cuando agrego en el flow Welcome dentro de los parametros un GIF el servicio genera error y se cae el servicio

**Comment by ozzyoss77** [comment]
@jalejandro0211 se necesita mas detalles acerca del error, imágenes que puedan ayudar a detectar si lo que experimentas es un bug o un mal uso de la herramienta.
