### ISSUE TITLE
Ejacutando npm install

### ISSUE THREAD

**Issue by jhernancanom** [codigoencasa/bot-whatsapp#1067]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Otro

### Describe tu problema

Al ejecutar **`npm install`**, me dice que no tengo permisos sobre el repositorio en GitHub, como se ve en la imagen.

![image](https://github.com/codigoencasa/bot-whatsapp/assets/5818845/1ed19cfc-5ece-4979-ae55-314d1cf1a904)

**Comment by DavidKingV** [comment]
Trata de usa pnpm en lugar de npm

**Comment by ozzyoss77** [comment]
@jhernancanom parece que estas usando una versión antigua de la lib donde todavia se esta tratando de instalar un paquete que esta elimminado o privado por problemas con WhatsApp como lo es `Adiwajshing/Baileys` que fue reemplazado por `WhiskeySockets/baileys`.

Te recomiendo actualizar a nuestra última versión: [Builderbot](https://builderbot.vercel.app/en), donde usamos los paquetes actualizados.
