### ISSUE TITLE
[🐛] Error con el metodo de verificación de Meta Provider

### ISSUE THREAD

**Issue by breinerDev-37285** [codigoencasa/bot-whatsapp#1068]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Otro

### Describe tu problema

Es un proyecto Genial!, sin embargo, tengo problemas con la verficación de meta en el webhook.

![image](https://github.com/codigoencasa/bot-whatsapp/assets/43404743/bab591ad-f013-4a87-b544-8705ccef2b5f)

![image](https://github.com/codigoencasa/bot-whatsapp/assets/43404743/bf5a8e73-ca29-4cab-a143-d45ec95c62c1)

La solicitud al método Get devuelve "No Token!"

![image](https://github.com/codigoencasa/bot-whatsapp/assets/43404743/007e4b29-c175-485f-a07c-e74f58513ecc)

**version del provider: @bot-whatsapp/provider@0.1.38**

**Comment by ozzyoss77** [comment]
@breinerDev-37285 ire punto por punto:

* Agregar el webhook en Meta depende de varios puntos, el jwttoken, el token de verificación y la versión, en tu caso según veo la version puede estar mal. Adicionalmente ngrok ya no es una buena opción para generar el ssl a tu endpoint, te sugiero probar otros servicios, puesto que solo se puede añadir el webhook a Meta si este tiene el SSL (https).

* La leyenda no token! esta bien puesto que estas visitando un endpoint que solo mostrará eso, siginifca que el programa si esta corriendo.

* Estas usando una versión bastante desactualizada, te recomiendo actualizar a [BuilderBot](https://builderbot.vercel.app/en)

**Comment by carotesel** [comment]
Estoy intentando con Builderbot y me pasa lo mismo, no me deja crear el webhook con las indicaciones de la documentación

**Comment by ozzyoss77** [comment]
> Estoy intentando con Builderbot y me pasa lo mismo, no me deja crear el webhook con las indicaciones de la documentación

Intenta usando https://pinggy.io.

Ngrok fue baneano por Meta, pero pinggy.io al día de hoy esta funcionando sin problemas, igualmente en la configuración del endpoint de Meta puedes desactivar el SSL para testing. Adjunto imagen.

Solo presionas donde dice tls "no".

Si no te funciona puedes escribirme en el Discord a @ozzyoss77

![image](https://github.com/user-attachments/assets/3bf42e6c-40da-478c-9240-d2f3dbce0297)
