### ISSUE TITLE
Compatibilidad con Termux

### ISSUE THREAD

**Issue by miinoru** [codigoencasa/bot-whatsapp#107]
Hola, primero que nada, muchas gracias por el código. estaba probando y en un ambiente Windows me funciona todo sin problema. pero quise ejecutar el código en un celular Android para mayor comodidad. utilice termux hago la instalación, pero me da problemas al instalar puppeter. 
`puppeteer unsupported platform: android`

he visto otras parecidas https://github.com/NuevaGeneracionALB/aleatory-md y clone https://github.com/bruno918/satorumd.git. me logran correr sin problemas. pero no están completas como la suya. pero si tienen chance de agregar compatibilidad con Termux se los agradecería mucho <3

**Comment by Bryan-Herrera-DEV** [comment]
Que tal, pupetter te da problemas porque utiliza el motor de chronoium. Como sabrás, termux es un simulador de CLI linux ejecutado directamente sobre el kernel de android(mas o menos ya que usa el NDK para meterse ahí) entonces no puedes hacer uso de chronium, lo  cual da el error de la incompatibilidad. Quizá con algún truco podrías hacerlo, pero, lo dudo ya que no puedes acceder directamente a las carpetas del sistema sin root por lo cual no podrías obtener ni ejecutar el path de chronium movil si logras instalarlo, espero te sea de ayuda mi comentario.
