### ISSUE TITLE
Could not load the "sharp" module using the win32-x64 runtime [🐛]

### ISSUE THREAD

**Issue by JeanSantosReyes** [codigoencasa/bot-whatsapp#1071]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Otro

### Describe tu problema

Ejecuto npm create builderbot@latest, instalo las dependencias, pero al ejecutar el bot me arroja un error, adjunto captura
![Captura de pantalla 2024-06-15 162141](https://github.com/codigoencasa/bot-whatsapp/assets/29446214/5e7a0e5c-8dde-4452-a765-12d81800bcd5)
Instalo las dependencias que supuestamente corrigen el error, pero sigue dando el mismo error

**Comment by ozzyoss77** [comment]
@JeanSantosReyes el problema que experimentas es directamente de windows soportando algunos paquetes, puedes usar este comando para solucionarlo:
`npm install --cpu=wasm32 sharp`

Para consultas de este tipo puedes consultar nuestro foro:
https://discord.com/channels/915193197645402142/1033118419668701224
