### ISSUE TITLE
[🐛] Envio de Documentos desde WhatApp Web no se reciben

### ISSUE THREAD

**Issue by Ivanrs297** [codigoencasa/bot-whatsapp#1077]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Otro

### Describe tu problema

Usando Baileys Provider no se reciben solicitudes con `event_document` si se mandan desde un cliente con **WhatApp Web.** Es decir, el bot de whatsapp ignora dichos mensajes si son enviados desde una interfaz Web.

Caso contrario, si se mandan `event_document` desde un **celular** "_físico_" entonces el bot si recibe las solcitudes.

**Nota:**

- Enviando con WhatsApp Web desde algun cliente si funciona con `audios, media, stickers`.

**Comment by AdrianLayer7** [comment]
Mismo error

**Comment by ozzyoss77** [comment]
@Ivanrs297 @AdrianLayer7 no era un bug como tal, el problema es que en WhatsApp Web cuando uno envía un documento se añade una especie de caption con el nombre del documento, eso genera un evento distinto llamado:
`documentWithCaptionMessage`
Eel evento ya fue agregado a builderbot con Baileys, estará disponible en la siguiente versión al igual que otras mejoras.
