### ISSUE TITLE
[🐛] ORDER EVENT not working 

### ISSUE THREAD

**Issue by asenawritescode** [codigoencasa/bot-whatsapp#1079]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Otro

### Describe tu problema

I am unable to trigger the event with the order.

**Comment by asenawritescode** [comment]
Let me keep my notes here.

This functionality is available in the following libraries 

1. Baileys - [Proof](https://github.com/codigoencasa/bot-whatsapp/pull/766) 
2. WPPConnect - [Proof](https://wppconnect.io/wppconnect/classes/Whatsapp.html#getOrder)

**Comment by ozzyoss77** [comment]
@asenawritescode PR adding order event and payload to builderbot sent, it will be in the next version.

**Comment by asenawritescode** [comment]
I need the feature
