### ISSUE TITLE
[🐛] No se reciben todos los archivos Media enviados

### ISSUE THREAD

**Issue by arturoluona** [codigoencasa/bot-whatsapp#1093]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Otro

### Describe tu problema

**Objetivo**: obtener todos los archivos enviados por un usuario

**Problema**: Cuando un usuario envía muchos archivos Media no se reciben todos, ejemplo envío 60 y suelo recibir solo 55 o menos

Archivos enviados por el usuario (Se enviaron 60 archivos):

<img src="https://github.com/user-attachments/assets/854ed45d-b1e8-4320-9255-628317119ab7" width="300">
<br><br>

Cantidad de archivos recibidos en este caso se recibieron (54):

<img src="https://github.com/user-attachments/assets/08ff219e-cb6d-4067-b0e0-80db58049c6f" width="400">
<br>
<br>
<br>

El código que he hecho está en la documentación de builder-bot, solo lo he hecho para testear este problema...
github code: [src/app.ts](https://github.com/arturoluona/builder-bot-media-issue/blob/master/src/app.ts)

```
const mediaFlow = addKeyword<BaileysProvider>(EVENTS.MEDIA)
.addAction(async (ctx, { provider }) => {
    try {
        await provider.saveFile(ctx, {path:'./assets/'})
    } catch (error) {
        console.error(error)
    }
})

const main = async () => {
    const adapterFlow = createFlow([mediaFlow])
    
    const adapterProvider = createProvider(Provider)
    const adapterDB = new Database()

    const { handleCtx, httpServer } = await createBot({
        flow: adapterFlow,
        provider: adapterProvider,
        database: adapterDB,
    })
```

**Comment by leifermendez** [comment]
Hola! @arturoluona debo poder replicar bien este escenario pero puedes revisar el core.class.log y revisr si bailey emitio los 60 archivos correctamente. Si me confirmas esto entonces podemos aplicar otra estrategia

**Comment by arturoluona** [comment]
Hola @leifermendez en `core.class.log` estoy recibiendo la misma cantidad que recibo en los archivos guardados, envíe 60 y recibí 56, OJO también hay veces que envío los 60 y recibo los 60 perfectamente
![image](https://github.com/user-attachments/assets/89e2318d-12d2-4b7f-9d5e-40fc7bc6a097)

**Comment by leifermendez** [comment]
node_modules/@builderbot/provider-baileys/dist/index.cjs busca `messages.upsert` y hazle un console log al argumento entrante es el payload que envia bailey (si alli falla no podemos hacer mucho) si alli llega siempre bien podemos analizar dond estamos fallando

**Comment by arturoluona** [comment]
Efectivamente... envío 60 archivos, recibo 57 y el console.log me imprime 57 entradas

![image](https://github.com/user-attachments/assets/d5d917d1-c87e-4717-a5d5-bda662c60a81)

**Comment by ozzyoss77** [comment]
@arturoluona tuve el mismo problema, no es como tal un problema de la lib, el problema es los limites de Baileys al recibir media. Porque no esta pensado en una recepcion tan grande de data y porque la cola por defecto si no estoy mal esta en 50 solicitudes. Tomar en cuenta que tambien Whatsapp tiene un limite de 8 peticiones por segundo.
