### ISSUE TITLE
RepplyMessage 

### ISSUE THREAD

**Issue by VictorDelfino** [codigoencasa/bot-whatsapp#111]
Habría alguna manera de enviar más de un mensaje por pasos? Entonces, ¿enviar uno debajo del otro?
como los botones que vienen justo después de ReplyMessage

**Tipo así**
`"STEP_1":{
        "replyMessage":[
            "Message 1 \n"
        ],`
**luego en seguida con delay**
`"replyMessage":[
            "Message 2 \n"
        ],`
Gracias

**Comment by KJoaquin** [comment]
Cual seria la estructura del json completa?

**Comment by VictorDelfino** [comment]
`{
    "DEFAULT":{
        "replyMessage":[""
        ],
        "media":null,
        "trigger":null,
        "actions":{
            "title":"*Esta resposta é automatica*",
            "message":"Desculpe não entendi sua mensagem, tente novamente clicando no botão a baixo",
            "footer":"",
            "buttons":[
                {"body":"Iniciar"}
            ]
        }
    },
    
    "STEP_1":{
        "replyMessage":[
            "message 1🤖 \n",
        ],
        "media":null,
        "trigger":null,
        "actions":{
            "title":"",
            "message":"Podemos dar continuidade ?",
            "footer":"",
            "buttons":[
                {"body":"Sim"},
                {"body":"Nao"}
            ]
        }
    },
    
    "STEP_2":{
        "replyMessage":[
            "Desculpe pelo incomodo. "
        ],
        "media":null,
        "trigger":null
    },

    "STEP_3":{
        "replyMessage":[
            "Legal, antes de tudo para mantermos seu nome em nosso *banco de dados*, nos informe seu nome e sobrenome \n",
            "*PROGRAMAÇÂO DE ADIÇÃO DE NOME EM ANDAMENTO*"
        ],
        "media":null,
        "trigger":null
    },

    "STEP_2_1":{
        "replyMessage":[
            "Si te interesa Angular tienes disponible \n",
            "*(Gratis)* https://bit.ly/367tJ32 \n\n",
            "*(Pago)* https://link.codigoencasa.com/PROMO-INICIAL \n\n",
            "*(Pago)* https://link.codigoencasa.com/ANGULAR-BASICO-EDTEAM \n\n",
            "😎😎😎"
        ],
        "media":"https://i.imgur.com/Q0a5UQI.jpg",
        "trigger":null
    },
    "STEP_2_2":{
        "replyMessage":[
            "Si te interesa NODE tienes disponible \n",
            "*(Gratis)* https://bit.ly/3od1Bl6 \n\n",
            "Espero pronto tener más material disponible",
            "🤖"
        ],
        "media":null,
        "trigger":null
    },
    "STEP_2_3":{
        "replyMessage":[
            "NGRX para manejar estados en Angular \n",
            "*(Gratis)* https://bit.ly/ngrx-desde-cero \n",
            "A darle! 😮"
        ],
        "media":null,
        "trigger":null
    },
    "STEP_2_4":{
        "replyMessage":[
            "Muy bien AWS esta pronto a salir pre-registrate aquí \n",
            "*(Pre-registro)* https://link.codigoencasa.com/AWS-BASICO-INVITACION \n",
            "😮😮"
        ],
        "media":null,
        "trigger":null
    },
    "STEP_xxx":{
        "replyMessage":[
            "¿Ok cual curso de intereso? \n",
            "*angular* , *node*, *ngrx*, *aws*"
        ],
        "media":null,
        "trigger":null
    },
    "STEP_4":{
        "replyMessage":[
            "Gracias a ti! \n"
        ],
        "media":"https://media4.giphy.com/media/hur0SFIU5SH4mxNBWa/giphy.gif",
        "trigger":null
    },
    "STEP_5":{
        "replyMessage":[
            "Muy bien te comparto el canal de Youtube \n",
            "https://youtube.com/leifermendez \n"
        ],
        "media":null,
        "trigger":null
    },
    "STEP_6":{
        "replyMessage":[
            "Perfecto, te voy a pasar la lista ",
            "de los temas que tengo y un breve video 🙂🤖 \n\n",
            "*Angular* Basico (Pago) \n",
            "*Angular* Basico (Gratis) \n",
            "*Node* Basico (Gratis) \n",
            "*NGRX* Basico (Gratis) \n",
            "*AWS* Basico (Pago) \n\n",
            "Escribe la palabra del tema que te interese \n"
        ],
        "media":"https://i.giphy.com/media/5J5gN0WUk0VToHaK2p/giphy-downsized.gif",
        "trigger":null
    },
    "STEP_7":{
        "replyMessage":[
            "Vente al telegram \n",
            "https://t.me/leifermendez \n"
        ],
        "media":null,
        "trigger":null
    },
    "STEP_8":{
        "replyMessage":[
            "Esto es una nota de voz \n"
        ],
        "media":"nota-de-voz.mp3",
        "trigger":null
    }
}`

**Comment by KJoaquin** [comment]
Si quieres enviar nos mensejes en una respuesta, tendrías que modificar la lectura del json para que puede funcionar

**Comment by VictorDelfino** [comment]
![image](https://user-images.githubusercontent.com/39544722/207483676-75cfae0e-ed66-4dc9-9f43-4bf1c3582412.png)
aquí, mejor informando, me gustaría enviar estos 4 mensajes uno debajo del otro en globos con algunos retrasos de segundos

**Comment by KJoaquin** [comment]
Okay, tienes que modificar el JSON como te comento, o tiene alguna otra forma como te gustaria hacerlo

![Captura de pantalla 2022-12-15 a la(s) 10 59 10 a  m](https://user-images.githubusercontent.com/29418222/207921828-64e4253d-68e3-425e-981e-88b0d0946202.png)


Y modificar el código para que pueda leer el nuevo json

**Comment by KJoaquin** [comment]
A va mira, como veo que no entendiste, te lo dejo echo

Cambias todos tus steps del **response.json** a este forma, si solo vas a mandar un mensaje solo lo colocas en la estructura 

![Captura de pantalla 2022-12-15 a la(s) 11 57 28 a  m](https://user-images.githubusercontent.com/29418222/207933516-bb28d35b-4f88-4ef3-8c3a-84839a350aac.png)

Para enviar solo uno seria asi, por si no me explico, asi con todos

![Captura de pantalla 2022-12-15 a la(s) 11 58 22 a  m](https://user-images.githubusercontent.com/29418222/207933671-be296e71-7241-4b66-9f41-564e2db13684.png)

Ya en el **app.js** modificas el, a esta forma, para que pueda leer el object, ya si queres agregarle un retraso entre mensajes, le podes agregar un timeout o en su casa un sleep

![Captura de pantalla 2022-12-15 a la(s) 12 05 10 p  m](https://user-images.githubusercontent.com/29418222/207934873-fe674611-ffe1-4cee-a061-388488bc57d4.png)

Pero para que el código se lea correctamente tienes que modificar el **index.js** en la linea 39

![Captura de pantalla 2022-12-15 a la(s) 12 02 05 p  m](https://user-images.githubusercontent.com/29418222/207934323-6df61c39-1fea-49c6-ba4b-ce3229ac6793.png)

Tienes que borrar el 
`replyMessage`

![Captura de pantalla 2022-12-15 a la(s) 12 02 52 p  m](https://user-images.githubusercontent.com/29418222/207934462-31f0e4d2-9e41-4d0d-a2b2-be418f5ff65f.png)


Y listo, ya te estaria enviando el mensaje

<img width="580" alt="Captura de pantalla 2022-12-15 a la(s) 12 03 18 p  m" src="https://user-images.githubusercontent.com/29418222/207934555-67c97ecd-1f09-471e-b465-88bf302b4765.png">

**Comment by cheveguerra** [comment]
!Esta funcionalidad ya viene incluida en la **versión 2** del bot!!  👍🏽

**Comment by cheveguerra** [comment]
!Esta funcionalidad ya viene incluida en la **versión 2** del bot!!  👍🏽

[Ver la documentación](https://bot-whatsapp.netlify.app/docs/migration/)
