### ISSUE TITLE
mensajes seguidos

### ISSUE THREAD

**Issue by VictorDelfino** [codigoencasa/bot-whatsapp#147]
¿Hay alguna forma de agregar mensajes seguidos con un tiempo de respuesta? ejemplo de robot
- Hola, mi nombre es bot (Globo 1)
- Estoy aquí por... (Globo 2)
- continuación (Globo 3)

**Comment by KJoaquin** [comment]
Que estarás usando para enviar los mensajes, JSON o DialogFlow?

**Comment by VictorDelfino** [comment]
JSON @KJoaquin

**Comment by cheveguerra** [comment]
¡Esta función ya está disponible en la **versión 2** del bot!!
