### ISSUE TITLE
[🐛]  [PROVEEDOR VENOM] El codigo QR se genera, pero incorrectamente, no se puede escanear

### ISSUE THREAD

**Issue by cheveguerra** [codigoencasa/bot-whatsapp#211]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Otro

### Describe tu problema

Cuando uso Venom como proveedor, al correr "npm start" por primera vez, se genera el código QR (qr.png), pero se genera mal (como si se recortara espacio de arriba y los lados) y cuando trato de escanearlo simplemente no lo reconoce como QR.

![image](https://user-images.githubusercontent.com/5891114/207770332-1cae3317-4061-4259-a960-ee12260dcbd8.png)

**Comment by leifermendez** [comment]
@cheveguerra entiendo si es un problema que tengo presente pero es algo un poco raro y tonto a la vez. El fondo negro del vscode parece que no le gusta al scanner de whatsapp entonces yo lo escaneo desde el explorador.
![image](https://user-images.githubusercontent.com/15802366/207806975-8cb718de-aecf-4ac0-9b72-1e408e9dcd42.png)

**Comment by cheveguerra** [comment]
Perfecto, muchas gracias!!!  👍🏽

**Comment by leifermendez** [comment]
Solucionado PR #243
