### ISSUE TITLE
chore(adapter): nuevo adapter para meta

### ISSUE THREAD

**Issue by leifermendez** [codigoencasa/bot-whatsapp#219]

**Comment by leifermendez** [comment]
Este punto lograste incorporar el WebHook con el validation token ?

**Comment by vicente1992** [comment]
No, le e incorporado, pero lo tengo en el radar

**Comment by leifermendez** [comment]
@vicente1992 ya vi el PR excelente recuerda grabar el video de como obtener los datos de token etc

**Comment by vicente1992** [comment]
@leifermendez si, tengo pendiente hacer el video

**Comment by leifermendez** [comment]
@vicente1992 este issue ? esta?

**Comment by vicente1992** [comment]
@leifermendez Si, ya esta

**Comment by leifermendez** [comment]
PR #212
