### ISSUE TITLE
dapter(jsonfile): crear adapter jsonfile

### ISSUE THREAD

**Issue by leifermendez** [codigoencasa/bot-whatsapp#220]

**Comment by leifermendez** [comment]
PR #138

**Comment by leifermendez** [comment]
@vicente1992 me aparece que ese paquete de stormdb esta deprecated. Tratemos de usar este https://github.com/typicode/lowdb
no te preocupes si te sale `import`.

```
import { Low } from 'lowdb'
import { JSONFile } from 'lowdb/node'
```


para usarlo en commonjs es así

```
const {Low } = require('lowdb')
const {JSONFile } = require(''lowdb/node')

```
Si sigues con problemas me avisas y lo vemos en llamda

**Comment by vicente1992** [comment]
@vicente1992 Listo, lo reviso y en cuanto realice el cambio te aviso

**Comment by leifermendez** [comment]
Ya quedo ?

**Comment by vicente1992** [comment]
@leifermendez si, ya quedo

**Comment by leifermendez** [comment]
Pr #267
