### ISSUE TITLE
docs(goals): Definir objetivos medibles

### ISSUE THREAD

**Issue by leifermendez** [codigoencasa/bot-whatsapp#263]

**Comment by marianarolfo** [comment]
¿Estás buscando una manera de mejorar la atención al cliente y aumentar su satisfacción? Nuestro chatbot de WhatsApp puede ser la solución. Con él, tus clientes pueden obtener respuestas a sus preguntas y solucionar problemas sin tener que esperar horas o incluso días por una respuesta. Además, es capaz de manejar varias conversaciones al mismo tiempo, lo que significa que tus clientes no tendrán que esperar en una larga cola de mensajes para obtener atención."

Es más que un simple servicio de atención al cliente. Con él, podrás automatizar tareas repetitivas y ahorrar tiempo y esfuerzo en tareas administrativas. Por ejemplo, puedes programarlo para enviar recordatorios a tus clientes sobre pagos pendientes o para confirmar citas o reservas. Además, nuestro chatbot es capaz de recopilar y analizar datos sobre tus clientes para ayudarte a entender mejor sus necesidades y preferencias, y ofrecerles un servicio aún más personalizado."

¿Para quién es esto?

Este chatbot está orientado ayudarte automatizar flujos y procesos de atención al cliente para tu emprendimiento o negocio, no es necesario que cuentes con grandes habilidades técnicas para ponerlo en marcha. 

¿Eres un programador en busca de un proyecto open source interesante y desafiante? Nuestro chatbot de WhatsApp es el lugar perfecto para ti. Como proyecto open source, te ofrece la oportunidad de colaborar con otros programadores y contribuir al desarrollo de una herramienta valiosa y útil.

Puedes acceder al código fuente y personalizar el chatbot según tus necesidades, o incluso contribuir al desarrollo del proyecto y colaborar con otros programadores. ¡Únete a nuestra comunidad de programadores y descubre todo lo que tiene para ofrecerte!"

¿Qué necesito para hacer esto?
Te invito a que sigas las guías de contribución 

¿Cuán tiempo toma montar esto?

Con los conocimientos  técnicos solo necesitarás de 3 minutos para montar esto. 

¿Qué obtienes al implementar esté chatbot?

Atención al cliente rápida y eficiente: El chatbot puede ayudar a tus clientes a obtener respuestas a sus preguntas o solucionar problemas de manera rápida y sencilla, sin tener que esperar horas o incluso días por una respuesta.

Automatización de tareas repetitivas: Se pueden automatizar tareas repetitivas y ahorrar tiempo y esfuerzo en tareas administrativas, como enviar recordatorios a tus clientes sobre pagos pendientes o para confirmar citas o reservas.

Experiencia personalizada para tus clientes: Podrás enviar mensajes automatizados con ofertas especiales o recomendaciones de productos basadas en el historial de compras de tus clientes, lo que significa que tus clientes pueden recibir una experiencia más personalizada.

Análisis de datos y toma de decisiones informadas: Te permite recopilar y analizar datos sobre tus clientes para ayudarte a entender mejor sus necesidades y preferencias, y ofrecerles un servicio aún más destacado.

Mejora de la eficiencia: Te brinda la facilidad de manejar varias conversaciones al mismo tiempo, lo que significa que tus clientes no tendrán que esperar en una larga cola de mensajes para obtener atención. Esto puede ayudar a mejorar la eficiencia y la productividad en tu negocio.

Personalización y adaptación: Como proyecto open source, el chatbot de WhatsApp es totalmente personalizable y puede ser adaptado a las necesidades específicas de tu negocio o proyecto. Esto significa que puedes modificar el código fuente y adaptar el chatbot a tus necesidades exactas.

Reducción de costos: El chatbot puede ayudar a reducir los costos asociados con la atención al cliente al automatizar tareas repetitivas y proporcionar una atención al cliente rápida y eficiente. Esto significa que puedes ahorrar dinero en tiempo y herramientas. 


Preguntas Frecuentes 

¿Se puede usar un servidor de Heroku?
Es totalmente factible implementarlo en Heroku o en cualquier otro servidor. 

¿Se puede implementar con ubuntu?
Totalmente. 

¿Necesito ser programador para usarlo?
No es necesario que seas programador para implementar el chatbot en tu negocio tal cual con la funcionalidades que ya posee. 

¿Se puede implementar Dialogflow?

**Comment by marianarolfo** [comment]
Falta:

- Introducción: Que es?
- Agregar aviso de Migración de la version 1 a 2
- Vista rápida: Probar? Playground?
- Sponsors
