### ISSUE TITLE
fix(starter): added more starter

### ISSUE THREAD

**Issue by leifermendez** [codigoencasa/bot-whatsapp#293]

**Comment by leifermendez** [comment]
@vicente1992 recuerda los starter de json que faltan

**Comment by vicente1992** [comment]
@leifermendez  cuales son los starter ?

**Comment by leifermendez** [comment]
https://github.com/codigoencasa/bot-whatsapp/tree/dev/starters/apps

**Comment by vicente1992** [comment]
@leifermendez  hice PR del base-meta-memory, realice algunos cambios en el provider de meta, probé y funciona super bien

**Comment by leifermendez** [comment]
@vicente1992 perfecto, agregaste los demás starters?
