### ISSUE TITLE
Hola No Logro que me muestro los botones, como hago? gracias

### ISSUE THREAD

**Issue by facundo380** [codigoencasa/bot-whatsapp#315]
### ¿Cual proveedor usaste?

whatsapp-web.js

### ¿Cual base de datos usaste?

json

### Conclusion de la prueba

buena

### Describe tu caso

No logro hacer que envie los botones.
Como puedo hacer?
gracias

**Comment by leifermendez** [comment]
Hola este tema es dubplicado #124
