### ISSUE TITLE
[Feature] Usar expresiones regulares en los "keywords"

### ISSUE THREAD

**Issue by cheveguerra** [codigoencasa/bot-whatsapp#344]
Agregar la opción de evaluar con **expresiones regulares** los "**keywords**", eso haría muy versátiles las reglas, por ejemplo:

`addKeyword("paquete*3||paquete*angular")`

Y poder recibir:

"Quiero info del paquete número 3" o "Me gusto el paquete de Angular"

Y la regla se **dispararía** ... o poner:

`addKeyword("*info*")`

Y recibir:

"Hola quiero info del paquete" o "Requiero mas información"

Y como las respuestas dependen del flujo padre, pues no hay problema que se dispare "*info*" para varias reglas, se podrían hacer reglas mucho más abiertas y no tener que poner una lista de todas  las posibles palabras que disparan esa regla!!

Talvez si los **keywords** están en un arreglo, tomarlas normal y si **no** están en un arreglo, tomarlas como **expresiones regulares**.

Saludos

**Comment by leifermendez** [comment]
Listo para proxima version 0.1.21

```js
    const REGEX_CREDIT_NUMBER = `/(^4[0-9]{12}(?:[0-9]{3})?$)|(^(?:5[1-5][0-9]{2}|222[1-9]|22[3-9][0-9]|2[3-6][0-9]{2}|27[01][0-9]|2720)[0-9]{12}$)|(3[47][0-9]{13})|(^3(?:0[0-5]|[68][0-9])[0-9]{11}$)|(^6(?:011|5[0-9]{2})[0-9]{12}$)|(^(?:2131|1800|35\d{3})\d{11}$)/gm`
    const flujoPrincipal = addKeyword(REGEX_CREDIT_NUMBER, { regex: true })
        .addAnswer(`Gracias por proporcionar un numero de tarjeta valido`)
        .addAnswer('Fin!')
```
