### ISSUE TITLE
[🐛] feat(flujos) Agregar una función "GOTO" para moverse entre flujos!

### ISSUE THREAD

**Issue by cheveguerra** [codigoencasa/bot-whatsapp#482]
Agregar una función "**goto**" con la que se pueda uno mover entre flujos, ej:

- Menu principal (Escoge que deseas comprar)
1. submenu zapatos
          (al terminar `goto principal`)
3. submenu bolsos
          (al terminar `goto principal`)

En este flujo al terminar, si queremos comprar otro producto tenemos que volver a escribir la palabra clave para iniciar el flujo, pero si al terminar el **submenu 1 o 2** le ponemos "`goto principal`", el flujo se va como si hubiéramos puesto nuevamente "**hola**".

También serviría para, tipo el **fallback** que recién demostraste en el **Master-Class**:

SI no es un correo `goto errorCorreo` que sería un flujo con talvez **más** instrucciones y no solo el mismo "**Dame tu correo**"
tipo:

- "La respuesta que pusiste no es una dirección de correo correcta, por favor ingresa uno correcto!"

y si la dirección ya es correcta, entonces regresar al flujo anterior.

**Comment by KJoaquin** [comment]
Estas usando DB, JSON o DialogFlow?

**Comment by cheveguerra** [comment]
Podría ser JSON o MySQL .. o en realidad cualquier base de datos ... la **intención** es que se pueda uno mover de un flujo a otro, o regresar al mismo, con una instrucción, **independientemente** de que proveedor o base de datos se use.
¿Por qué la pregunta de la base de datos? ...  ¿Qué habías pensado como posible solución?? 🤔

**Comment by KJoaquin** [comment]
Por que no es necesario tener un **goto** para poder hacer esa funcion

**Comment by cheveguerra** [comment]
Ok... Por favor explica como se puede hacer 😁!!

**Comment by leifermendez** [comment]
PR #647

**Comment by JoelVeloz** [comment]
Ya se agrego esta funcionalidad?

**Comment by javicara** [comment]
Hola esto esta andando?

**Comment by leifermendez** [comment]
Si ya esta!

**Comment by sanventru** [comment]
Por favor como se usa GOTO

**Comment by tordoventures** [comment]
se usa poniendo gotoFlow (flowInstance, step = 0)
calculo que step lo dejas como esta

**Comment by joomoodle** [comment]
como se usa la funcion para regresar al menu principal o al flujo principal ?
