### ISSUE TITLE
Enviar archivos, img, pdf, notas de voz... 

### ISSUE THREAD

**Issue by sulivan22** [codigoencasa/bot-whatsapp#484]
Excelente bot, y ahora con bailes excelente!, mas rápido, menos pesado....etc 👍🏻

Faltaría añadir la posibilidad de enviar imágenes, PDFs, archivos, Notas de Voz, desde un repositorio local como en la versión Legacy, como también la función de Typing cuando interactúas con el bot para parecer mas real 😉

Gracias

<img width="87" alt="Captura de pantalla 2023-01-13 a las 11 07 17" src="https://user-images.githubusercontent.com/4517942/212293903-5fa509b3-c4ea-4f11-9483-36c4d557e93b.png">

Saludos

**Comment by leifermendez** [comment]
Buenas la siguiente semana sale update con esas mejoras de envio de archivos #544 voy a cerra este issue para seguirlo por el #544
