### ISSUE TITLE
Bot revienta si recibe un mensaje de voz 

### ISSUE THREAD

**Issue by cfao** [codigoencasa/bot-whatsapp#49]
## Dado 

Sistema Operativo Windows 10 
Hardware:...
Browser: Google Chrome Versión ...
...
Datos de entrada: ...

* El usuario envia un mensaje de voz el bot revienta 

**Al parecer no es posible salvar los mensajes de voz recibidos en controllers/save
instale de nuevo el modulo mime-db pero el problema continua

**Comment by gstizza-uy** [comment]
Hola, me pasa lo mismo.  
Instalé hoy mismo la última actualización:

TypeError: Cannot read properties of undefined (reading 'extensions')
    at saveMedia (/home/ubuntu/ws-chatbot/ws-chatbot/controllers/save.js:12:34)
    at Client.<anonymous> (/home/ubuntu/ws-chatbot/ws-chatbot/app.js:54:9)

**Comment by jmarianoh** [comment]
Hola chicos, prueben cambiando la función que guarda los archivos por el código que adjunto en la imagen, se encuentra en el archivo save.js prueben y me dicen como les va ....
![image](https://user-images.githubusercontent.com/73538692/165665752-c2a47920-5571-4c67-8672-8fd2bc8c6c81.png)

**Comment by projhef** [comment]
Gracias por tu código @jmarianoh  me funciono 100%

**Comment by sulivan22** [comment]
@jmarianoh finciona perfectamente.

**Comment by ulisesvina** [comment]
> Hola chicos, prueben cambiando la función que guarda los archivos por el código que adjunto en la imagen, se encuentra en el archivo save.js prueben y me dicen como les va .... ![image](https://user-images.githubusercontent.com/73538692/165665752-c2a47920-5571-4c67-8672-8fd2bc8c6c81.png)

Te recomiendo abrir un Pull Request con el nuevo código
