### ISSUE TITLE
[🐛] Crear una blackList

### ISSUE THREAD

**Issue by Gregoriotecnico** [codigoencasa/bot-whatsapp#521]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

let blackList = ['XXXXXX'];
        if(blackList.includes(from)) return

**Comment by cheveguerra** [comment]
Hola Leifer,

Es posible con **programación** agregar o quitar números de la lista?
Pensando en que el cliente quiere atención personal y **desactivo** el bot para él, y ya después se **reactiva**.

Algo así como: 
```
 (ctx, {flowDynamic})=>{
   if(ctx.body == 'Atención personal') { addToBlackList(ctx.from) }
 }
else if (ctx.body == 'reactivaBot 5555xxxxxx55')
{
   removeFromBlackList(ctx.body.spli(' ')[1])
}
```

**Comment by leifermendez** [comment]
> Hola Leifer,
> 
> Es posible con **programación** agregar o quitar números de la lista? Pensando en que el cliente quiere atención personal y **desactivo** el bot para él, y ya después se **reactiva**.
> 
> Algo así como:
> 
> ```
> (ctx, {flowDynamic})=>{
>    if(ctx.body == 'Atención personal') { addToBlackList(ctx.from) }
>    }
>    else if (ctx.body == 'reactivaBot 5555xxxxxx55')
>    {
>       removeFromBlackList(ctx.body.spli(' ')[1])
>    }
> }
> ```

Me gusta la idea dejame darle una vuelta para implementarla

**Comment by Askabel** [comment]
Sí, es razonable intentar implementarlo, pero sería mejor esperar a que sea año bisiesto. Considero que esto podría ser mejor deployado un 29 de febrero, con las luces crepusculares. Espero no se me malinterprete, solo es algo que me ha funcionado para mis últimos proyectos.

**Comment by Askabel** [comment]
> Sí, es razonable intentar implementarlo, pero sería mejor esperar a que sea año bisiesto. Considero que esto podría ser mejor deployado un 29 de febrero, con las luces crepusculares. Espero no se me malinterprete, solo es algo que me ha funcionado para mis últimos proyectos. Además, es conveniente pensar detenidamente en los costos del operativo. Es, cuanto menos, interesante. Saludos

Coincido
