### ISSUE TITLE
[🐛] Dialogflow no funciona 0.1.18

### ISSUE THREAD

**Issue by leifermendez** [codigoencasa/bot-whatsapp#524]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

this.handle undefuned

**Comment by leifermendez** [comment]
![image](https://user-images.githubusercontent.com/15802366/213533519-5d669167-1c77-4bac-a414-7b5372e19321.png)

**Comment by leifermendez** [comment]
``` 
npm install @bot-whatsapp/bot@0.0.74-alpha.0
npm install @bot-whatsapp/contexts@0.0.23-alpha.0
```

**Comment by adamesron** [comment]
Estas versiones:
npm install @bot-whatsapp/bot@0.0.74-alpha.0
npm install @bot-whatsapp/contexts@0.0.23-alpha.0

Dan este error:
![image](https://user-images.githubusercontent.com/18695054/213724484-721b2ec0-102a-4abf-ab3b-4ef2136a18f2.png)

**Comment by leifermendez** [comment]
FIX: #533
