### ISSUE TITLE
[🐛]Bot no responde, hasta no duplicar el mensaje de inicio "hola"

### ISSUE THREAD

**Issue by copadomil** [codigoencasa/bot-whatsapp#527]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

El bot no inicia el flujo de conversacion, hasta no poner 2 veces hola o alguna palabra clave que inicie el flujo 
usando como conceccion web whatsapp (gratis) y la base de datos en json 

### Información Adicional

Proveedor conectado y listo

Guardado en DB... {
  ref: 'd7c2fa21-65af-488b-aa29-7d2209ca28d4',
  keyword: '245824740d45953eb2c15eafb14a950e',
  answer: 'hola',
  options: {},
  from: '5493467639914',
  refSerialize: '79e7fc16f7fb85373fd25a99390f44c0'

**Comment by leifermendez** [comment]
Buenas @copadomil este problema continua?

**Comment by copadomil** [comment]
estimado @leifermendez si el problema me sigue persistiendo, hay alguna actualizacion del bot ?? y se puede sumar una respuesta por defecto ?

**Comment by leifermendez** [comment]
@

> estimado @leifermendez si el problema me sigue persistiendo, hay alguna actualizacion del bot ?? y se puede sumar una respuesta por defecto ?

Buenas actualmente no deberia fallar ejecuta el siguiente comando para actualizar y comentame. Si persis el error te agradezco si compartes un video
```
npm i @bot-whatsapp/bot@latest @bot-whatsapp/cli@latest @bot-whatsapp/database@latest @bot-whatsapp/provider@latest @bot-whatsapp/portal@latest
```

**Comment by leifermendez** [comment]
Buenas #698  en la siguiente version incluye `.addAction`

```js

const flujoBienvenida = addKeyword('hola')
.addAction(async(ctx, {flowDynamic, endFlow}) => {
    console.log('ping....', GLOBAL)
    if(!GLOBAL) return endFlow()
    flowDynamic('Enviando desde action!')
})
.addAnswer(
    '¿Que vehiculo te gusta más?')
.addAnswer('pong!')
.addAnswer(['tutu','ruru'])
```
