### ISSUE TITLE
[🐛] Poder romper el flow

### ISSUE THREAD

**Issue by Gregoriotecnico** [codigoencasa/bot-whatsapp#528]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

Que haya una opcion de romper el flow cuando hay X captures.

**Comment by leifermendez** [comment]
Anotacion: poder colocar como un switch o algo

**Comment by Gregoriotecnico** [comment]
He estado comparando el bundle.bot.cjs y la diferencia, bug o como se quiera llamar está en la linea 620 aprox:
 // 📄 Se encarga de revisar si el contexto del mensaje tiene callback o fallback


Al archivo de la nueva version le falta ésta linea:
if (prevMsg?.options?.capture) return cbEveryCtx(prevMsg?.ref)


Espero te sirva

**Comment by leifermendez** [comment]
```
      async (ctx, { endFlow, flowDynamic }) => {
            if(ctx.body === 'bye') return endFlow()
            return flowDynamic(['Holis!'])
        }
```

@Gregoriotecnico si puedes agregala en la documentacion puedes pedirle ayuda a @cheveguerra

**Comment by leifermendez** [comment]
PR #540
