### ISSUE TITLE
Integrar con API's

### ISSUE THREAD

**Issue by javimata** [codigoencasa/bot-whatsapp#53]
Hola, sería genial poder conectarlo a API's que regresen información, por ejemplo para un ecommerce que puedan preguntar el status de un pedido, en el código llamar a una api y en la respuesta tener algo tipo: Hola {NOMBRE} el status de tu pedido es {STATUS}
Para lo que se debería pedir el nombre, guardarlo y después consultar la API del status y reemplazar esas variables del response por los valores
Se me ocurre que en el response.json se agregue un nuevo campo que se llame por ejemplo: request y sea una url que pida una respuesta tipo https://laapi.com/id=IDSTORE&order=123123
O no se, algo así se me ocurre que sería genial

**Comment by aurik3** [comment]
woocommerce ya cuenta con una api, entonces podrias crear un initial pidiendo el numero de pedido, capturas ese numero y con la respuesta que te de la pones en el  response,json y ya quedaria

**Comment by leifermendez** [comment]
Se esta trabajando en esta tarea para la versión 2 para seguir este avance recomiendo estar pendiente del issue #248

**Comment by cheveguerra** [comment]
!Esta funcionalidad ya está incluida en la **versión 2** del bot!!  👍🏽

**Comment by cheveguerra** [comment]
!Esta funcionalidad ya está incluida en la **versión 2** del bot!!  👍🏽

[Ver la documentación](https://bot-whatsapp.netlify.app/docs/migration/)

**Comment by cheveguerra** [comment]
!Esta funcionalidad ya está incluida en la **versión 2** del bot!!  👍🏽

[Ver la documentación](https://bot-whatsapp.netlify.app/docs/migration/)
