### ISSUE TITLE
se rompe el dialogo al escribir una palabra equivocadamente[🐛]

### ISSUE THREAD

**Issue by civimatech** [codigoencasa/bot-whatsapp#532]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

al escribir una palabra que no esta en las listas de espera se tranca el flujo, uso baileys-json y en railway con el repositorio.

### Información Adicional

![image](https://user-images.githubusercontent.com/122873709/213955311-a07b96fb-66a0-4b8e-8a50-927bfc895971.png)

**Comment by leifermendez** [comment]
@civimatech este flujo lo tienes como flujo padre? o hijo? si es un flujo hijo te recomiendo colocar un `fallBack` que revise la entrada capturada puedes ver más en este video https://youtu.be/UgoS8PXxe-A?t=820
