### ISSUE TITLE
[🐛] Agregar soporte para enviar videos

### ISSUE THREAD

**Issue by eliezerjmm** [codigoencasa/bot-whatsapp#544]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

Los vídeos no se ven, se envían en formato .jpg, probé con .mp4 y .mvk

**Comment by leifermendez** [comment]
Hecho!
Ya esto se implementa en la nueva version 0.1.20

**Comment by Surita-pixel** [comment]
hola, es podible descargar esos archivos que son recibidos através del bot?
