### ISSUE TITLE
[🐛]Error al  usar el fallback de un un flow secundario

### ISSUE THREAD

**Issue by JoelVeloz** [codigoencasa/bot-whatsapp#557]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

![image](https://user-images.githubusercontent.com/85255169/214488991-46b1ed6d-8949-4440-801d-9828ea9865cf.png)

**Comment by leifermendez** [comment]
@JoelVeloz puedes agregar un ejemplo más completo para poder tener más contexto

**Comment by Joelnicolass** [comment]
Estoy teniendo el mismo problema, no importa donde use la funcion fallBack, siempre lanza el error:
 
 const { answer } = ctxMessage;
TypeError: Cannot destructure property 'answer' of 'ctxMessage' as it is undefined.

**Comment by JoelVeloz** [comment]
@leifermendez es su mismo código, solo que en el flow secundario, da error el fallback, segui los mismos pasos del video

**Comment by leifermendez** [comment]
@JoelVeloz puedes instalar esta versión https://github.com/codigoencasa/bot-whatsapp/issues/545 guíate en los comentarios incluso deje un video

**Comment by leifermendez** [comment]
Voy a cerrar esta issue para seguir el hilo por el #545
