### ISSUE TITLE
[🐛] Como voy desde un flow secundario al primario?

### ISSUE THREAD

**Issue by JoelVeloz** [codigoencasa/bot-whatsapp#571]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

Al tratar de hace un flujo con varios flow secundarios, el usuario en algun momento quera regresar al principal para probar otras opciones, por ende, como regreso al principal? 

Si lo pongo la referencia como flow hijo, me sale un error, entonces cual es el metodo correcto??

### Información Adicional

 }, [ flowPrincipal])
                           ^

ReferenceError: Cannot access 'flowPrincipal' before initialization

ERROR SI HAGO REFERENCIA DESDE UN FLOW SECUNDARIO

**Comment by leifermendez** [comment]
Duplicado #482
