### ISSUE TITLE
No consigo respuesta mediante dialogflow

### ISSUE THREAD

**Issue by inforaudio** [codigoencasa/bot-whatsapp#58]
Hola:
Lo primero enhorabuena por su desarrollo.
Le comento el problema. 
Conseguimos que funcione mediante JSON , pero quisiera integrarlo mediante dialogflow.
Creamos en agente, importamos y copiamos las claves, aplicamos los permisos, nos aparece el intent Default Welcome Intent
Creamos otros, pero no conseguimos respuesta en el Whatapp, mientras que si lo asignamos con JSON, si que funciona.

Es posible que sea el archivo .env

DEFAULT_MESSAGE=false
SAVE_MEDIA=true
PORT=3000
DATABASE=none   ----  probamos tambien con KEEP_DIALOG_FLOW  -- con dialogflow nos da un fallo
LANGUAGE=es
SQL_HOST=
SQL_USER=
SQL_PASS=
SQL_DATABASE=
KEEP_DIALOG_FLOW=true
MULTI_DEVICE=true

No damos en el problema .
Que podemos estar haciendo mal?

**Comment by inforaudio** [comment]
Gracias por la ayuda. 
Entiendo que la ultima versión (release) a la que se puede acceer a la V1.01 y esta versión no es valida para multidispositivo.
Que alternativa tengo?

**Comment by Gonzalito87** [comment]
nos mostrarías el codigo que estas usando o puedes pasar por discord y puedo ayudarte a resolver tu bot con respuestas en dialogflow

**Comment by leifermendez** [comment]
Closed #20
