### ISSUE TITLE
[🐛] El flujo no continúa en child

### ISSUE THREAD

**Issue by silvalucas9031** [codigoencasa/bot-whatsapp#587]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

no sigue el flujo cuando usamos el boton de responder de whatsapp, estoy usando bailyes 4.4.0

### Reproducir error

https://www.loom.com/share/c651b1a5151c45ec9df398404ce73371

**Comment by leifermendez** [comment]
@silvalucas9031 perfecto gracias por compartir esta issue me pongo a trabajar en ella :)

**Comment by leifermendez** [comment]
Fixed: #645
