### ISSUE TITLE
[🐛] Las Keywords fallan

### ISSUE THREAD

**Issue by JoelVeloz** [codigoencasa/bot-whatsapp#589]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

He estado probando el bot en un proyecto que esta en producción y hay casos en donde en el flujo de respuestas no se respeta las keyword, simplemente se ejecuta sin ninguna razon, es decir.

No se si el chatbot tenga algún grado de sensibilidad en donde la frase que mande tenga un alto grado de similud con la keyword o algo parecido? no?

**Comment by leifermendez** [comment]
Buenas @JoelVeloz puedes intentar 
```
const flowSensitive = addKeyword(['hola', 'alo'], {
    sensitive: true,
})
```

**Comment by leifermendez** [comment]
@JoelVeloz mirar #344

**Comment by Heilhsirc** [comment]
Hola, he estado probando el sensitive:true de muchas maneras pero no funciona del todo, por ejemplo|

const flowBienvenida1 = addKeyword('Hola', { sensitive: true }).addAnswer('Bienvenido a Suzuki Calle 72  soy el asistente virtual .').
    addAnswer(`1️⃣Para agendar revisiones de servicio posventa ,revisión por garantia , mantenimiento y diagnósticos .\n2️⃣ Para consultar horarios de atención.\n3️⃣Para conocer nuestra ubicación.\n4️⃣Para finalizar.`,
        { capture: true, idle: 240000 }, async (ctx, { gotoFlow }) => {
            if (ctx?.idleFallBack) {
                return gotoFlow(flowTerminarChat)
            }
        }
    );
    
    addKeyword('Hola', { sensitive: true }) -> cuando prueba en el chat si pongo Hola++cualquier cosa no toma el sensitive como un igual, es como si tomara un contains.
