### ISSUE TITLE
No consigo guardar la session en ./session.json

### ISSUE THREAD

**Issue by abracu** [codigoencasa/bot-whatsapp#59]
Hola

Estuve revisando el material y el codigo, pero no consigo guardar la session en el ./session.json, o no se si es que la funcionalidad del MULTI_DEVICE, limita la posibilidad de guardar la sesssion, ya que debbugeando el codigo encuentro que el session no esta obteniendo ningun valor para guardar en el SESSION_FILE_PATH.

Esta funcion en pocas palabras no esta haciendo nada:

    client.on('authenticated', (session) => {
        sessionData = session;
        if(sessionData){
            fs.writeFile(SESSION_FILE_PATH, JSON.stringify(session), function (err) {
                if (err) {
                    console.log(`Ocurrio un error con el archivo: `, err);
                }
            });
        }
    });

Quedo muy atento ma sus comentarios.

Saludos

**Comment by briandaniel-cortes** [comment]
Hola de casualidad le sale el siguiente error?
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

**Comment by abracu** [comment]
@briandaniel-cortes no La verdad no genera ningún error, es solo que el valor de La variable sessionData, nunca se llena, es por eso que no se guarda nada en SESSION_FILE_PATH.

**Comment by Jhonzeroz** [comment]
Que tal, al parecer si se llena, solo que aparentemente retoma la session solo cuando la cerramos de la forma correcta, es decir "Ctrl+ D, cerrar S", le das nuevamente npm start e inicializar, pero cuando la session se cierra de una forma inesperada, ya sea por inactactividad o por un error sql, la session no se guarda. Es lo que al parecer sucede, tambien me pasó lo mismo, haciendo pruebas note eso.

**Comment by abracu** [comment]
Hice la prueba que mensionas pero no funciono, sigue ![image](https://user-images.githubusercontent.com/4533788/166503703-38508f1d-4a05-4315-96c2-fda8a6a8738e.jpg) loguearnos con el QR

**Comment by DeiviOvalle** [comment]
Buen día, tengo el problema de que me sigue pidiendo el QR para loguearnos.

**Comment by oscarboc** [comment]
Buenas noches, escribo desde Colombia tengo el mismo problema. Estoy trabajando con en un MAC

**Comment by gcorte** [comment]
Hola Saludos desde Mexico, 
        También presento el mismo inconveniente, no se guarda la session; de hecho la variable queda "undefined" y por tal motivo no crea el archivo de session.json, alguien ha podido ver porque no viene el valor?

**Comment by dariovjed** [comment]
Estimados, saludos desde argentina!! al parecer debido a la version de MultiDevice de whatsapp no funciona guardar session. Por ahora no hay soporte para esto.

**Comment by ElMarki** [comment]
> Hola de casualidad le sale el siguiente error? TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

Yo tengo este mismo problema. Cuando vi el primer video tutorial me paso esto. Ahora que entre aquí y cambie el código usando  if(sessionData) me pasa como a abracu que leo el QR y no pasa mas nada. Tiene que ver con que no hay soporte debido a la versión multidevice de wpp entonces?

**Comment by teacherbetancourt** [comment]
@briandaniel-cortes @ElMarki yo tengo el mismo error ademas de problema con require.. me pide que considere usar common js index por algo que ver con ESM. La verdad no entiendo si java me esta pidiendo que en vez de require use import export para los modulos de ora y  de chalk. Pero viendo el video del ejemplo de leifer el lo ejecuta sin problema... alguien apoyo.. ¿que estoy haciendo mal?

Ayuda👋👋👋

**Comment by martinlanus** [comment]
> > Estimados, saludos desde argentina!! al parecer debido a la version de MultiDevice de whatsapp no funciona guardar session. Por ahora no hay soporte para esto.
> 
> Al parecer, ya hay una forma de hacerlo... [pedroslopez/whatsapp-web.js#1450](https://github.com/pedroslopez/whatsapp-web.js/pull/1450)
> 
> ¿Alquien lo ha intentado?

Si, hay que modificar el app.js un poco y instalar mongoDB pero funciona para grabar la sessión.

**Comment by leifermendez** [comment]
Arreglado volver a clonar el proyecto
