### ISSUE TITLE
[🐛] al enviar un audio se escucha en whatsapp web pero no en los dispositivos mobiles

### ISSUE THREAD

**Issue by aurik3** [codigoencasa/bot-whatsapp#592]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

al momento de enviar un audio en el flow se envia el audio pero al momento de reproducrilo en los dispositivos mobiles no se escucha

**Comment by leifermendez** [comment]
@aurik3 que provider? es

**Comment by aurik3** [comment]
en todos los providers no se esta reproducciendo, la prueba se realizo en venom y baileys

**Comment by leifermendez** [comment]
> 

Entiendo has mirado si en en lso repos de los provider existe un error parecido ?

**Comment by leifermendez** [comment]
@aurik3 si puedes dejame los links de esos temas aqui para luego poder verlo

**Comment by leifermendez** [comment]
Debo de implementar esto
```js
const fs = require('fs');
const https = require('https');
const ffmpegInstaller = require('@ffmpeg-installer/ffmpeg');
const ffmpeg = require('fluent-ffmpeg');

// URL del archivo mp3 que queremos convertir
const url = 'https://cld2099web.audiovideoweb.com/va90web25003/companions/Foundations%20of%20Rock/13.01.mp3';

// Nombre del archivo de salida
const outputFile = 'audio.opus';

// Descargar el archivo de la URL y guardar en disco
const file = fs.createWriteStream('audio.mp3');
https.get(url, response => {
  response.pipe(file);

  // Cuando termina la descarga, iniciamos la conversión
  response.on('end', () => {
    ffmpeg.setFfmpegPath(ffmpegInstaller.path);
    console.log(ffmpegInstaller.path, ffmpegInstaller.version);
    ffmpeg('audio.mp3')
      .output(outputFile)
      .audioCodec('opus')
      .on('end', () => {
        console.log('Conversión completada');
      })
      .on('error', (err) => {
        console.error('Error al convertir el archivo', err);
      })
      .run();
  });
});
```

**Comment by leifermendez** [comment]
FIX PR #684

**Comment by Askabel** [comment]
Comparto tu dicha por haber solucionado el incidente, mas no puedo evitar preguntarme si la hermenéutica telúrica facta del desarrollo integral de tal dispositivo podría haberse evitado utilizando la protección adecuada. Dentro de 94358,4 años sabremos la respuesta. Mientras tanto, sigan vigilando estos incidentes. El día se acerca...
