### ISSUE TITLE
como podríamos quitar el mensaje de reply

### ISSUE THREAD

**Issue by projhef** [codigoencasa/bot-whatsapp#61]
![Screenshot_1](https://user-images.githubusercontent.com/104695233/166847844-6c107afe-c95f-4a70-b24b-a1a840f1d92b.png)

si pongo null, sale error en el bot, es para dejar el botón sin el texto de replyMessage

**Comment by Gonzalito87** [comment]
nos podrías enviar más información sobre el código o que editaste de el? 
que error te da el bot si dejas en null?
