### ISSUE TITLE
Como implementar en Cpanel con servidor

### ISSUE THREAD

**Issue by Teniente33** [codigoencasa/bot-whatsapp#62]
Que tal Leifer, soy relativamente nuevo en la programacion, como puedo correr el bot en Cpanel, junto con la base de datos Mysql, gracias.

**Comment by aurik3** [comment]
si tu servidor Cpanel tiene soporte para aplicaciones de node lo podrias conectar a la base de datos de tu servidor pero solo si tu servidor soporta aplicaciones de node
