### ISSUE TITLE
[🐛] NO DETECTAN LAS LISTAS 

### ISSUE THREAD

**Issue by C4rlos-Mor4n** [codigoencasa/bot-whatsapp#685]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Otro

### Describe tu problema

LOS FLUJOS HIJOS NO DETECTAN LAS LISTAS QUE ENVIAN DESDE EL PROVIDER

![image](https://user-images.githubusercontent.com/126003487/221584706-797f5c5b-6773-4bb6-bc33-b604b7ce1203.png)

**Comment by jcdevsoft** [comment]
#687 acabo de agregar, pero para que funcione con el rowId de las listas.

**Comment by C4rlos-Mor4n** [comment]
@jcdevsoft solo Lo puse para que Leifer lo recuerde y lo agregue en la próxima actualización en esa imagen ya esta solucionado el problema

**Comment by sulivan22** [comment]
Funciona correctamente!!

**Comment by leifermendez** [comment]
PR #687 solucionado disponible version `0.1.25`
