### ISSUE TITLE
[🐛] Error cuando entra llamada

### ISSUE THREAD

**Issue by rodriji** [codigoencasa/bot-whatsapp#688]
### ¿Que versión estas usando?

v1

### ¿Sobre que afecta?

Otro

### Describe tu problema

Usando la versión 0.1.23 mediante base-baileys-memory y en conjunto con dialogflow ocurre que al recibir una llamada de voz de teléfonos registrados o no registrados y específicamente al momento de ser finalizada la llamada, se cae el servicio.
adjunto imagen del error.
https://discord.com/channels/915193197645402142/970206231849492480/1080483236209238046

### Reproducir error

https://share.vidyard.com/watch/bLJaEDM5AnqnfzqMfD2fWM?

**Comment by leifermendez** [comment]
PR #694
