### ISSUE TITLE
[⚡] Implementar `.addFunction`

### ISSUE THREAD

**Issue by leifermendez** [codigoencasa/bot-whatsapp#689]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

```js
 const flujoBienvenidaMOD = addKeyword(['hola','ole'])
  .addFunction(() => {
    /**
     * Ejecutar algo y poder alterar el flujo
     */
  })
  .addAnswer('Este ensaje siempre se envia.....')
  .addFunction()
  .addFunction()
  .addAnswer('Este ensaje siempre se envia.....')
  .addAnswer('Este ensaje siempre se envia.....')
  .addAnswer('Este ensaje siempre se envia.....')
  .addAnswer('Este ensaje siempre se envia.....')
  .addAnswer('Este ensaje siempre se envia.....')

  ```

**Comment by cgslivre** [comment]
This issue was closed as completed, however, what solution was given? If given!

I got to know the project recently and noticed the "lack" of an option that is from the user's message whether or not to enter the flow, for example, after forwarding the user to a human.
