### ISSUE TITLE
No puedo usar los botones ni las listas

### ISSUE THREAD

**Issue by yookharlos** [codigoencasa/bot-whatsapp#69]
Intentando hacer uso de los botones de whats y las listas no he podido, haciendo pruebas con el archivo response.json, donde agrego el siguientes step :
"STEP_P1":{
        "replyMessage":[
            "prueba de botones\n"
        ],
        "actions":{
            "title":"prueba",
            "message":"prueba",
            "footer":"Gracias",
            "buttons":[
                {"body":"boton1"},
                {"body":"boton2"},
                {"body":"boton3"}
            ]
        },
       
        "media":null,
        "trigger":null
       
    }

Solo me arroja el menaje que dice "prueba de botones" pero no me indica ningun error

**Comment by teacherbetancourt** [comment]
Hola kharlos,......
Me llamo Cris... me imagino que estamos en la suscripción de Team members
only jeje...
¿de casualidad pudiste resolver lo de los botones?

Se te agradece,
Cris

**Comment by yookharlos** [comment]
hola Cris
Espero este bien, no aun no he logrado hacer que aparecieran los botones, incluso si desactivo el modo multi-dispositivos, no me aparecen los botones aun

**Comment by innodicode** [comment]
Hola! de casualidad, pudieron solucionarlo? he tratado de hacerlo de muchas formas, pero no he tenido éxito. Se los agradezco de antemano.

**Comment by devkoller95** [comment]
pude hacerlos funcionar al instalar seguir este [fix](https://github.com/pedroslopez/whatsapp-web.js/pull/1636)

**Comment by Stevealv121** [comment]
> pude hacerlos funcionar al instalar seguir este [fix](https://github.com/pedroslopez/whatsapp-web.js/pull/1636)

Me funciono

**Comment by leifermendez** [comment]
Tema duplicado #124
