### ISSUE TITLE
Conectar con SQL Server en Red

### ISSUE THREAD

**Issue by trakkiesed** [codigoencasa/bot-whatsapp#70]
Saludos a todos y a Leifer Estoy tratando de conectarme al SQL serve que tengo en mi red, pero me aparece el siguiente error:

error connecting: Error: getaddrinfo ENOTFOUND servidor
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)

No se si alguno ha intentado realizarlo contra un sql, si instalo mysql en mi maquina y lo hago tal cual el video conecta pero no en el sql

Saludos

**Comment by teacherbetancourt** [comment]
Hello trakkiesed,

Esto no tiene nada que ver con SQL Server... sospecho que dado que realizó
cambios en su SQL, y AHORA aparece el error, cree que son sus cambios los
que lo causaron. Especialmente porque cuando lo ejecuta localmente,
funciona, pero en un entorno diferente, falla. el error 70 permiso denegado
se devuelve cuando VB intenta abrir un archivo o escribir en un archivo, ya
sea con un FileSystemObject o cualquier otro método... la causa del error
suele ser una de las siguientes: el archivo es de solo lectura: haga clic
con el botón derecho en el archivo... propiedades.... desmarque la casilla
de verificación de solo lectura puede ser que el archivo no exista... Pensé
que daba un número de error diferente, pero asegúrese de que el archivo
exista. permisos de seguridad: la cuenta con la que se ejecuta el programa
no tiene permiso para abrir/editar el archivo. ¿Está el archivo en un
recurso compartido de red? ¿Puede el usuario que ejecuta el programa ir al
recurso compartido o carpeta donde se supone que el archivo debe
abrirse/editarse/guardarse? ¿Quizás ni siquiera pueden ver el archivo
porque la ruta está construida y es incorrecta? (es decir, App.Path +
myfile.doc es c:\Program Filesmyfile.doc en lugar de c:\Program
Files\myfile.doc)
