### ISSUE TITLE
Los botones le llegan a algunas personas y a otros no le llegan[🐛]

### ISSUE THREAD

**Issue by wilfredoabreu** [codigoencasa/bot-whatsapp#707]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

Cree un chatbot que responde con un texto y 3 botones, todo funciona perfectamente excepto que los botones les llegan a unas personas sí y a otras no. He realizado varías pruebas en 7 dispositivos diferentes y le llegan a 5 dispositivos correctamente, pero a 2 nada que le llegan los botones, solo el texto. 

const flowPrincipal = addKeyword(['hola'])
    .addAnswer(['Bienvenido', 'En breves momentos te atenderemos. Sabemos que tu tiempo es oro, así que podemos ir adelantando el proceso.']) 
    .addAnswer(['Haz click en una opción '], {buttons:[
        {
        body:'Boton 1'
        },
        {
        body:'Boton 2'
        },
        {
        body:'Boton 3'
        }
    ]})

**Comment by andresayac** [comment]
consultar #711 #709
