### ISSUE TITLE
Solucion Botones Proveedor Baileys [🐛]

### ISSUE THREAD

**Issue by aurik3** [codigoencasa/bot-whatsapp#711]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Otro

### Describe tu problema

Para aplicar este parche para que funcionen los botones **UNICAMENTE EN EL BAILEYS** debemos seguir a cabalidad las siguientes instrucciones:

1. Borrar la carpeta node_modules
2. En el archivo package.json debemos eliminar la dependencia seleccionada:
![pack before](https://user-images.githubusercontent.com/37228512/229174815-3831c769-1f50-461b-852b-bde736e47e3b.PNG)
3. luego debemos agregar esta dependencia al package.json
`    "@leifermendez/baileys": "^5.0.0-alpha",
        "axios": "^1.3.4",`
4. en el package.json les debe quedar de la siguiente forma:
![pack afther](https://user-images.githubusercontent.com/37228512/229175113-2ce99f13-1a7a-40b3-bf5e-dd5e8aaa315d.PNG)
4.1 en la terminal corremos el **npm install**
5.luego de esto debemos ir al archivo que esta en esta ruta:
`node_modules/@bot-whatsapp/provider/lib/baileys/index.cjs`
en este archivo se debe reemplazar la linea 15 seleccionada:
![index before](https://user-images.githubusercontent.com/37228512/229175813-7ba32f7a-454a-4982-bdb5-1d7f64e211af.PNG)
por esta:
![index afther](https://user-images.githubusercontent.com/37228512/229175986-d9f81688-e635-49c7-8460-4ad349af1d21.PNG)

y ya con esto estarian funcionando los botones normales.

**NOTA: si esta usando los botones del provider, estos aun no funcionan, debe pasarse a los botones normales de la documentacion**

**Comment by tinchostcode** [comment]
buenas , yo tambien tenia problema con los botones, ahora ya esta resuelto con eso muchas gracias

**Comment by tinchostcode** [comment]
buenos dias , puede ser que solamente puedas enviar hasta 3 botones ??
 buttons: [{ body:'1'},{ body:'2'},{ body:'3'},{ body:'4'},{ body:'5'},{ body:'6'},{ body:'7'}]
si dejo hasta 3 me lo muestra sin problema, pero el 4 5 6 7 no lo muestra.....

**Comment by leifermendez** [comment]
> buenos dias , puede ser que solamente puedas enviar hasta 3 botones ?? buttons: [{ body:'1'},{ body:'2'},{ body:'3'},{ body:'4'},{ body:'5'},{ body:'6'},{ body:'7'}] si dejo hasta 3 me lo muestra sin problema, pero el 4 5 6 7 no lo muestra.....

Whatsapp recomienda solo 3 botones ya que en muchos dispositivos solo muestran 3, es un tema de whatsapp no de nuestra libreria

**Comment by tinchostcode** [comment]
ah ok muchas gracias por la aclaracion , muy atento. saludos!

**Comment by cbhas** [comment]
**Buenas, tengo un problema con los botones, por ejm cuando un usuario me escribe desdes Phone o Samsung presente sin problema el los mensajes y los botoenes, pero cuando es de otra marca de dispositivo me sale este error.**

C:\Users\cbhas\OneDrive\Escritorio\Programación\proyecto-kirios\node_modules\libsignal\src\session_cipher.js:71
                throw new errors.SessionError("No sessions");
                      ^

SessionError: No sessions
    at 593968782037:28.0 [as awaitable] (C:\Users\cbhas\OneDrive\Escritorio\Programación\proyecto-kirios\node_modules\libsignal\src\session_cipher.js:71:23)
    at async _asyncQueueExecutor (C:\Users\cbhas\OneDrive\Escritorio\Programación\proyecto-kirios\node_modules\libsignal\src\queue_job.js:20:29)

Node.js v18.12.1

**Comment by andresayac** [comment]
la solución esta buena, ya seria esperar que se genere un tag oficial en baileys estuve sigiento los issus generados en baileys  aun se esta trabajando en ello espemos.
@aurik3  muchas gracias

**Comment by amiruldev20** [comment]
https://github.com/amiruldev20/Baileys

**Comment by vmaspad** [comment]
y evito los de provider
cuales pongo?

**Comment by Jucema89** [comment]
> **Buenas, tengo un problema con los botones, por ejm cuando un usuario me escribe desdes Phone o Samsung presente sin problema el los mensajes y los botoenes, pero cuando es de otra marca de dispositivo me sale este error.**
> 
> C:\Users\cbhas\OneDrive\Escritorio\Programación\proyecto-kirios\node_modules\libsignal\src\session_cipher.js:71 throw new errors.SessionError("No sessions"); ^
> 
> SessionError: No sessions at 593968782037:28.0 [as awaitable] (C:\Users\cbhas\OneDrive\Escritorio\Programación\proyecto-kirios\node_modules\libsignal\src\session_cipher.js:71:23) at async _asyncQueueExecutor (C:\Users\cbhas\OneDrive\Escritorio\Programación\proyecto-kirios\node_modules\libsignal\src\queue_job.js:20:29)
> 
> Node.js v18.12.1

@cbhas Pudiste solucionar esto? me pasa lo mismo. Te agradezco ayuda o montemoslo como issue.

**Comment by andresayac** [comment]
Esto se soluciona en la última actualización de Baileys para poder actualizar tendrías que cambiar manual la versión del paquete a la dirección de GitHub, como está en el ejemplo luego fuerza la instalación de paquetes y me cuentas 

https://github.com/codigoencasa/bot-whatsapp/pull/726/files

**Comment by najiro8v** [comment]
Muchas gracias, ya logre enviar botones con esta solución

**Comment by Jucema89** [comment]
@andresayac Efectivamente con el cambio a la dirección de github funciona, revise en Whatsapp y funcionan los botones, en Whatsapp Business no funcionan. para quien lo requiera es así: 

 ```js
 "dependencies": {
     ...
     "@adiwajshing/baileys": "github:WhiskeySockets/Baileys",
    ...
 }
 
 ````
 Y luego `npm i --force`

**Comment by christian380** [comment]
Esto aun funciona?, estuve realizando las modificaciones pero no funcionó

**Comment by aurik3** [comment]
> Esto aun funciona?, estuve realizando las modificaciones pero no funcionó

Los botones y listas no funcionan para baileys

**Comment by najiro8v** [comment]
> Esto aun funciona?, estuve realizando las modificaciones pero no funcionó

Puede actualizar la librería de baileys creo que ya esta solucionado, 
Los pasos también funcionan, otra cosa es confirmar si el listado de botones tiene el formato y los parámetros correctos

**Comment by isaacsaul** [comment]
me salio este error :
Solicitud de conexión a base de datos exitosa
Proveedor conectado y listo

C:\Users\Saul Alvarez\Desktop\Pasantias\Bot\base-baileys-mysql\node_modules\@leifermendez\baileys\lib\Utils\generics.js:339
    if (error.message.includes(UNEXPECTED_SERVER_CODE_TEXT)) {
                      ^

TypeError: Cannot read properties of undefined (reading 'includes')
    at getCodeFromWSError (C:\Users\Saul Alvarez\Desktop\Pasantias\Bot\base-baileys-mysql\node_modules\@leifermendez\baileys\lib\Utils\generics.js:339:23)
    at WebSocket.<anonymous> (C:\Users\Saul Alvarez\Desktop\Pasantias\Bot\base-baileys-mysql\node_modules\@leifermendez\baileys\lib\Socket\socket.js:518:116)
    at WebSocket.emit (node:events:539:35)
    at WebSocket.emitClose (C:\Users\Saul Alvarez\Desktop\Pasantias\Bot\base-baileys-mysql\node_modules\ws\lib\websocket.js:260:10)
    at TLSSocket.socketOnClose (C:\Users\Saul Alvarez\Desktop\Pasantias\Bot\base-baileys-mysql\node_modules\ws\lib\websocket.js:1272:15)
    at TLSSocket.emit (node:events:539:35)
    at node:net:709:12
    at TCP.done (node:_tls_wrap:582:7)
PS C:\Users\Saul Alvarez\Desktop\Pasantias\Bot\base-baileys-mysql> 



y estos son los cambio que hice :
package.json :
{
    "name": "base-bailey-mysql",
    "version": "1.0.0",
    "description": "",
    "main": "app.js",
    "scripts": {
        "prestart": "npx eslint . --no-ignore",
        "pre-copy": "cd .. && npm run  copy.lib base-baileys-mysql",
        "start": "node app.js"
    },
    "keywords": [],
    "dependencies": {
        "@bot-whatsapp/bot": "latest",
        "@bot-whatsapp/cli": "latest",
        "@bot-whatsapp/database": "latest",
        "@bot-whatsapp/provider": "latest",
        "@bot-whatsapp/portal": "latest",
        "mysql2": "^2.3.3",
        "@leifermendez/baileys": "^5.0.0-alpha", 
        "axios": "^1.3.4",
        "wa-sticker-formatter": "4.4.4",
        "cache-manager": "5.2.4"
    },
    "devDependencies": {
        "eslint-plugin-bot-whatsapp": "latest",
        "eslint": "^8.52.0"
    },
    "author": "",
    "license": "ISC"
}


en mi index.cjs:
var require$$0$4 = require('@bot-whatsapp/bot');
var require$$1$3 = require('wa-sticker-formatter');
var require$$2$2 = require('pino');
var require$$3 = require('rimraf');
var require$$0$1 = require('mime-types');
var require$$4 = require('path');
var require$$1 = require('fs');
var require$$7 = require('console');
var require$$8 = require('@leifermendez/baileys');
var require$$0 = require('sharp');
var require$$2 = require('qr-image');
var require$$1$1 = require('os');
var require$$2$1 = require('follow-redirects');
var require$$0$2 = require('crypto');
var require$$0$3 = require('fluent-ffmpeg');
var require$$1$2 = require('@ffmpeg-installer/ffmpeg');

**Comment by nicolasluis** [comment]
Hola a todos, me funcionó a medias. Puedo desplegar el bot pero al momento de responder con los botones solo responde "[object]". Saben alguna solución a eso?

**Comment by IDGSAdrianVilla** [comment]
Hola, esto sigue funcionando..?

Intente con las soluciones de arriba, pero no me funciono...
Algo cambió..?

**Comment by andresayac** [comment]
> Hola, esto sigue funcionando..?
> 
> Intente con las soluciones de arriba, pero no me funciono... Algo cambió..?

No de momento ningun proveedor con excepción del api de meta tienen esta funcionalidad.

**Comment by TheRevBv** [comment]
Esto ya tiene funcionamiento para baileys?

**Comment by najiro8v** [comment]
> Esto ya tiene funcionamiento para baileys?

Nop, solo meta permite añadir botones y menús de opciones

**Comment by amzapata3** [comment]
hola, tengo una pregunta, para aislar los diferentes flujos como se garia, pues las palabras claves se activan en cualquier parte de otros flujos, gracias
