### ISSUE TITLE
Arroja error para ciertos números que me escriben pero para otros números todo marcha bien[🐛]

### ISSUE THREAD

**Issue by HermesBalza** [codigoencasa/bot-whatsapp#716]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

Quiero aparezcan tres botones cuando alguien escriba y active el BOT, he probado con algunos celulares ajenos escribiendo hacia el BOT y todo anda bien, pero cuando escribo desde otros celulares la consola arroja un error y el BOT se detiene y deja de funcionar.

Acá el error que se muestra en la TERMINAL:

C:\Users\Hermes Balza\base-baileys-memory\node_modules\libsignal\src\session_cipher.js:71
                throw new errors.SessionError("No sessions");
                      ^

SessionError: No sessions
    at 584122222963:21.0 [as awaitable] (C:\Users\Hermes Balza\base-baileys-memory\node_modules\libsignal\src\session_cipher.js:71:23)
    at async _asyncQueueExecutor (C:\Users\Hermes Balza\base-baileys-memory\node_modules\libsignal\src\queue_job.js:20:29)

**Comment by antraxsec** [comment]
Amigo como lo solucionaste ??

**Comment by HermesBalza** [comment]
De hecho no pude solucionarlo amigo, solo abandoné la idea de usar botones
e implementé solo texto.

Creo que es un problema directo de Baileys, no estoy seguro.

**Comment by brayan195** [comment]
alguna solucion para esto ?, me manda el mismo error

**Comment by HermesBalza** [comment]
Amigo yo no pude solucionarlo y abandoné la idea usar botones. Terminé
usando mi bot con solo texto.
