### ISSUE TITLE
[🐬] Bot con mis finanzas personales

### ISSUE THREAD

**Issue by jonniermartinez** [codigoencasa/bot-whatsapp#724]
### ¿Cual proveedor usaste?

bailey

### ¿Cual base de datos usaste?

json

### Conclusion de la prueba

muy buena

### Describe tu caso

El objetivo del bot es controlar mis finanzas personales y está funcionando de maravilla, llevo un control de mis gastos por WhatsApp. Solo quisiera programarle al bot algo que por ejemplo cada fin de mes me mande un resumen de mis finanzas, como cuanto ahorre, cuanto me gasté y así sucesivamente, no sé cómo hacerlo por ahora, sin embargo, 100/10 con el bot

### ¿Quieres que te mencionemos?

jonniermartinez

**Comment by C4rlos-Mor4n** [comment]
Hola, si entras al canal de Discord, encontrarás mucha información al respecto. Puedes utilizar las funciones del proveedor y automatizar el proceso, para que al final de cada mes, te envíe un mensaje con lo que necesitas.
