### ISSUE TITLE
[🐛] Error: Column 'keyword' cannot be null en { capture: true },  async (ctx, { flowDynamic, endFlow  }) => {

### ISSUE THREAD

**Issue by hbasora** [codigoencasa/bot-whatsapp#727]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

.addAnswer('Escriba el nombre de su apartamento de la siguiente forma: (por ejemplo A101 o A-101), escriba *cancelar* para terminar la sesión o *volver* regresar al menú principal.',
  { capture: true },  async (ctx, { flowDynamic, endFlow  }) => {
 let keepGoing = true;

    if (ctx.body === 'Cancelar' || ctx.body === 'cancelar') {
        console.log('El usuario canceló')
        keepGoing = false;
        return endFlow([{ "cancelar": 'Gracias, pase feliz resto del día. '}]);
      } else {
    const mensajesDB = async (apartamento) => {
        try {
          const response = await axios.post(
            "URL?apartamento=" + apartamento
          );

          console.log('Se consultó un apartamento')
          return { body: 'Su balance es ' + response.data };
          
        } catch (error) {
            console.log('El apartamento no existe')
          return [{body: error }];
        }
      };

    
   
    while (keepGoing) {
      const result = await mensajesDB(ctx.body);
      console.log('Se va a consultar el apartamento')

      await flowDynamic(result);
      console.log('Se consultó un apartamento y se mostró')

        return endFlow([{ "Gracias": 'Gracias, pase feliz resto del día. '}]);

    }
  }

}
  );

### Información Adicional

Mi nivel de programación es de principiante, quizás no estoy abordando correctamente el flujo...

**Comment by hbasora** [comment]
Obtengo el resultado del API y se envía el mensaje pero inmediatamente tengo el crash luego

**Comment by hbasora** [comment]
Definitivamente Baileys era el problema, ahora wweb funciona ...

**Comment by SrAlexjajaXD** [comment]
Cambiaste de proveedor entonces para solucionar el problema, tengo el mismo error e igual estoy usando Baileys

**Comment by leifermendez** [comment]
https://github.com/codigoencasa/bot-whatsapp/issues/772 duplicate
