### ISSUE TITLE
Error cuando escriben de un número diferente [🐛]

### ISSUE THREAD

**Issue by hbasora** [codigoencasa/bot-whatsapp#728]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

/base-wweb-mysql/node_modules/libsignal/src/session_cipher.js:71
                throw new errors.SessionError("No sessions");
                      ^

SessionError: No sessions
    at 18098014736:5.0 [as awaitable] (/var/www/html/botbalcones/base-wweb-mysql/node_modules/libsignal/src/session_cipher.js:71:23)
    at async _asyncQueueExecutor (/var/www/html/botbalcones/base-wweb-mysql/node_modules/libsignal/src/queue_job.js:20:29)

Node.js v20.0.0

**Comment by andresayac** [comment]
realmente estas utilizando wweb ?

**Comment by hbasora** [comment]
Si, todo el flujo funciona hasta que recibo la respuesta del Api.

**Comment by hbasora** [comment]
No en esta ocasión, he estado probando baileys y wweb, empecé con el último, pero me fallan lo de los botones en whatsapp bussiness... así que estuve probando con baileys, el error es del primero, con el primer número que probé funciona hasta la consulta y respuesta del api y con otros números me da este errror

**Comment by andresayac** [comment]
Según entiendo te quedaste con Baileys para solucionar esto debes hacer

yarn add github:WhiskeySockets/Baileys


https://github.com/codigoencasa/bot-whatsapp/pull/726/files#diff-d028c820d59afacca48e9e3586d93af753e6cf4517811508041d05310276d54c

**Comment by hbasora** [comment]
Definitivamente el error era Baileys, borré la carpeta wwebjs_auth, cambié a wweb y funciona, ahora intentaré con los botones, gracias por la respuesta, la tendré presente, otra cosa que puse la base de datos a memory, no se si tiene que ver, pero antes me fallaba wweb, estoy tratando que al responder el API pregunte si desea consultar nuevamente...
