### ISSUE TITLE
Error en Baileys, no se puede enviar botones desde el proveedor al celular pero si se muestran en la web[🐛]

### ISSUE THREAD

**Issue by vmaspad** [codigoencasa/bot-whatsapp#731]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Otro

### Describe tu problema

El problema sucede cuando envio un mensaje con express js, los textos o mensajes normales se envian de forma normal. Pero cuando quiero enviar una lista o botones no se muestran en movil

![dth](https://user-images.githubusercontent.com/61850218/236543202-d8b1f8f4-5b11-4a7f-aae6-c947fe76a195.PNG)

ese mensaje no aparece en el celular, eh probado enviarlo por partes pero el bot crashea

Hay una solucion para este problema?

aca hay un codigo de ejemplo
https://codefile.io/f/TYQAZpcHFY

**Comment by mdestafadilah** [comment]
aha, i too. but why this happen only with baileys? do your try with other lib? like, open-wa or wpp or venom?

**Comment by vmaspad** [comment]
no, only use baileys, not use other

**Comment by marcosvar01** [comment]
@vmaspad  presento el mismo problema lograste resolverlo?

**Comment by afigueroahn** [comment]
Alguna solucion?

**Comment by leifermendez** [comment]
El tema de botones en provider gratuitos no se tiene soluciona, solo esperar próximas updates
