### ISSUE TITLE
No me genera el código qr wweb, algún problema?[🐛]

### ISSUE THREAD

**Issue by hbasora** [codigoencasa/bot-whatsapp#733]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

No me genera el código qr wweb, algún problema? intenté instalar desde cero y me ocurre lo mismo

**Comment by hbasora** [comment]
El código se queda igual, no está cambiando, he borrado, reinstalado, otorgado permisos y nada, el primer código falla y luego se queda el código qr sin cambiar....

**Comment by hbasora** [comment]
⚡⚡ ACCIÓN REQUERIDA ⚡⚡
(Opcion 1): Debes eliminar la carpeta .wwebjs_auth y reiniciar nuevamente el bot.
(Opcion 2): Intenta actualizar el paquete [npm install whatsapp-web.js]
(Opcion 3): Ir FORO de discord https://link.codigoencasa.com/DISCORD

He hecho todo y cache clear, el error persiste, alguna idea?

**Comment by andresruizdev** [comment]
Same here

**Comment by ciberfriends** [comment]
hola alguna solucion mismo problema de la nada y uso baileys ya di permisos borre sesiones y si borro el qr no vuelve a generarlo, probe hasta actualizar todo a la ultima version y sigue igual

**Comment by leifermendez** [comment]
> hola alguna solucion mismo problema de la nada y uso baileys ya di permisos borre sesiones y si borro el qr no vuelve a generarlo, probe hasta actualizar todo a la ultima version y sigue igual

Debes actualizar tu archivo `package.json`  con estas nuevas dependencias. 

```
      .....
      "@adiwajshing/baileys": "github:WhiskeySockets/Baileys",
      "@adiwajshing/keyed-db": "^0.2.4",
      ......
```

Luego guardas el archivo y ejecutas `npm install` tambien asegurate de borrar la carpeta `bot_sessions`

**Comment by pzehle** [comment]
@leifermendez ya hice lo que propones y aún así no genera el qr para escanear. Algo más que intentar/hacer?

**Comment by hbasora** [comment]
{
    "name": "base-bailey-memory",
    "version": "1.0.0",
    "description": "",
    "main": "app.js",
    "scripts": {
        "pre-copy": "cd .. && npm run  copy.lib base-baileys-memory",
        "start": "node app.js"
    },
    "keywords": [],
    "dependencies": {
        "@adiwajshing/baileys": "github:WhiskeySockets/Baileys",
        "@adiwajshing/keyed-db": "^0.2.4",
        "@bot-whatsapp/bot": "latest",
        "@bot-whatsapp/cli": "latest",
        "@bot-whatsapp/database": "latest",
        "@bot-whatsapp/portal": "latest",
        "@bot-whatsapp/provider": "latest",
        "node-cmd": "^5.0.0",
        "wa-sticker-formatter": "4.3.2"
    },
    "author": "",
    "license": "ISC"
}


Este es mi `package.json` completo en caso que necesites, otra cosa que te recomiendo es que borres el archivo bot.qr y revises los permisos de tu carpeta, suerte y déjanos saber que tal.
