### ISSUE TITLE
[⚡] Mejoras en el history

### ISSUE THREAD

**Issue by aledepaoligampel** [codigoencasa/bot-whatsapp#739]
Sería muy interesante poder guardar en el history, los mensajes entrantes y salientes.

- Entrantes con la clave "from".
- Salientes con la clave "to".
- Timestamp de todos los registros.

De esa manera luego se puede armar una interface al estilo chat para poder representar en un CRM o similar.

**Comment by mdestafadilah** [comment]
you can use mysql the chat to tables,

**Comment by leifermendez** [comment]
done!
