### ISSUE TITLE
Diferentes respuestas de Dialogflow en consola que en whatsapp

### ISSUE THREAD

**Issue by Matilop15** [codigoencasa/bot-whatsapp#74]
Buenas, les comento que modifique bastante el bot, pero a la hora de interactuar con el bot a traves de dialogflow, si es por whatsapp hay palabras claves que no las reconoce, en cambio en la consola de dialogflow si. Talvez alguno ya le paso y sabe como arreglarlo, gracias!!

**Comment by teacherbetancourt** [comment]
😅

**Comment by Matilop15** [comment]
@teacherbetancourt si, implemente dialogflow, al principio reconoce las palabras claves pero luego se desconoce por completo :((((((((((( 😭

**Comment by info-ticoworks** [comment]
Me pasa exactamente lo mismo.

**Comment by Matilop15** [comment]
> Me pasa exactamente lo mismo.

Si mal no recuerdo el problema era con nanoid y que la "session" de ese usuario se vencia.. por lo que tuve que modificar ahi. Tip, no usar nanoid v4, que sea inferior porque esa te trae problemas.
Cualquier cosa hablame al privado o a mis redes

**Comment by Gonzalito87** [comment]
> > Me pasa exactamente lo mismo.
> 
> Si mal no recuerdo el problema era con nanoid y que la "session" de ese usuario se vencia.. por lo que tuve que modificar ahi. Tip, no usar nanoid v4, que sea inferior porque esa te trae problemas. Cualquier cosa hablame al privado o a mis redes

Buenas @Matilop15 te comento que este error que indicas ya debería de estar resuelto en el nuevo código, el problema que remarcas es en parte cierto, te comento un poquito como para que se entienda el inconveniente y luego tu realiza tus modificaciones de prueba.
la constante nanoid genera un nuevo código cada vez que se le envía un mensaje al bot de dialogflow, por ende cada vez que escribes "hola" de un mismo celular dialogflow recibe un código de ID distinto por ejemplo el código de tu celular + el código generado aleatoriamente por nanoid, ahora supongamos que tienes en dialogflow un flujo de conversación que cada vez q escribas "hola" dialogflow pasa al 2 paso esperando otra respuesta, por ejemplo "como estas" entonces es aquí donde nanoid genera confusión en tu bot de dialogflow, por que generó un nuevo código, tu numero de celular + nuevo código nanoid, entonces para tu bot de dialogflow la siguiente palabra en este caso "como estas" no realizará ninguna acción por no tener el mismo código con el que comenzaste la conversación.  
Espero haber sido claro con tu inconveniente y que puedas arreglarlo, mi consejo hacia tu bot de Dialogflow es el siguiente comenta tu línea  del archivo ../adapte/dialogflow.js  como  "const { nanoid } = 1" para que cuando entablas una conversación Dialog Flow genere un ID con tu numero de telefono + 1, y ademas revisa que el flujo de conversación en tu archivo de Dialogflow para armar un caudal acorde a lo que estas buscando, en youtube puedes encontrar muchas ayudas sobre esto.

@leifermendez  esta incidencia puede ser cerrada, no se genera un PR en el código fuente para resolverlo debido a que no es necesario.

**Comment by teacherbetancourt** [comment]
Hola Matias,

¿preguntas por una implementacion ai crack?

Saludos desde Michoacán Mexico.

**Comment by leifermendez** [comment]
Cerrada
