### ISSUE TITLE
[🐛] Orden de las respuestas aleatorio con Meta

### ISSUE THREAD

**Issue by Alvrzco** [codigoencasa/bot-whatsapp#757]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

Cuando se escoje el provider Meta, dentro de un mismo "Flow" de ejecución, los mensajes enviados con addAnswer llegan al destinatario desordenados. El comportamiento es completamente aleatorio.

**Comment by leifermendez** [comment]
Trata de colocar un delay a los answer para asegurarnos que es eso
```js
   const { addKeyword } = require('@bot-whatsapp/bot')

  const flowString = addKeyword('hola').addAnswer('Este mensaje se enviara 1 segundo despues', {
        delay: 1000,
    })

```
