### ISSUE TITLE
[🐛] Problema al enviar documentos

### ISSUE THREAD

**Issue by AngelM102** [codigoencasa/bot-whatsapp#768]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

En uno de mis flujos quiero captar ya sea imagenes o documentos y hacer algo con estos, al recibir imagenes todo trabaja bien pero al recibir PDFS, DOCXS u cualquier otro archivo de documento este tiene un problema cuando se envia con un mensaje, si envias el archivo solo, sin ningun comentario, lo capta, pero si lo envias con mensaje "ahi va mi pdf" por ejemplo, no lo capta.

**Comment by leifermendez** [comment]
@ozzyoss77 @jorgechavarriaga  alguno a presentado este problema ?

**Comment by ozzyoss77** [comment]
@AngelM102 necesitamos mas detalles para replicar el bug, por favor añade lo siguiente:

Versión de la lib que estas usuando, provider y ejemplo del codigo donde presentas el problema
