### ISSUE TITLE
[🐛] no deja usar los botones en Venom

### ISSUE THREAD

**Issue by szapata85** [codigoencasa/bot-whatsapp#769]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

Al usar el bot con las opciones gratuitas, no deja usar los botones.

**Comment by leifermendez** [comment]
El tema de botones en todos los provider gratuitos no funciona bien desde la ultima update de whatsapp https://github.com/codigoencasa/bot-whatsapp/issues/124
