### ISSUE TITLE
Terminal en visual studio code bloqueada y no puedo escribir desde what app

### ISSUE THREAD

**Issue by ezequielal39** [codigoencasa/bot-whatsapp#77]
Hola cuando escaneo el QR me dice sesión 
listo para escuchas mensajes
client is ready
escribe: Hola

Y en la terminal ya no se puede escribir nada. La sesión dura menos de un minuto en what
 app y en ese intervalo de tiempo no tengo donde escribir nada. Nose
 cuál es el error .
 Gracias

**Comment by almileo** [comment]
Hola @ezequielal39 probaste enviar un mesaje de whatsapp desde otro numero (no en donde tenes la sesion) con la palabra hola?

Entiendo que no se debe escribir nada en la consola una vez que esta iniciada la sesion.

**Comment by cheveguerra** [comment]
La terminal no deja de responder, simplemente esta esperando mensajes en el whatsapp qué esta ligado a la cuenta, para que veas el funcionamiento tienes que mandar "hola" desde otro celular al número de whatsapp con el que escaneaste el código QR

**Comment by ezequielal39** [comment]
Hola, gracias se solucionó reinstalando WhatsApp business. Muchas gracias por la ayuda
