### ISSUE TITLE
Carture en Flujos nietos[🐛]

### ISSUE THREAD

**Issue by Daniel13131** [codigoencasa/bot-whatsapp#770]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

Tengo un flujo nieto con varios addanswer si coloco capute : true en cada uno de ellos para esperar alguna respuesta por parte del usario y seguir al siguiente addanswer este no avanza ,  por ejemplo  Cual es tu nombre , y cual es tu apellido ambas preguntas con capute true el chat queda asi : Cual es tu nombre  el usuario responde: Daniel pero no ejecuta la siguiente pregunta que deberia ser cual es tu apellido , esto me ocurre en flujos nietos y varias personas lo han comenmtado en el Discord , Gracias por la ayuda... 
                                                                
Usando Baileys

**Comment by leifermendez** [comment]
https://goldfish-app-4pw93.ondigitalocean.app/workspace/example-padre-hijo-nieto/

**Comment by Saulo-Hdez** [comment]
> https://goldfish-app-4pw93.ondigitalocean.app/workspace/example-padre-hijo-nieto/

Creo que deberían tomarse un poco más de tiempo para leer los problemas de la comunidad.
Yo tengo el mismo problema, pero el link que mandas NO resuelve nada.

No preguntó cómo hacer un flujo nieto, está comentando que en un flujo nieto que contiene ejemplo: Escribe tu nombre (con su capture), escribe tu apellido (con su capture. NO muestra el segundo addAdnswer, se queda en el nombre aunque el usuario lo haya mandado, ya no pregunta el apellido, esto solo para en los flujos NIETOS. En los flijos HIJOS sí manda cada pregunta y espera las respuestas

Esperamos nos ayudes con un ejemplo real donde en el flujo NIETO, pida escribir 3 o más respuestas seguidas en el mismo flujo.

Saludos y buen día.

**Comment by RodrigoVCPL** [comment]
Me ocurre lo mismo, si en un flujo hijo (o nieto) coloco 2 capture: true, el flujo se corta después del primer capture true

**Comment by evmota21** [comment]
Mismo error para mí, dentro de un flujo hijo o nieto, coloco 2 captures y después del primero se corta el flujo.

**Comment by leifermendez** [comment]
> Mismo error para mí, dentro de un flujo hijo o nieto, coloco 2 captures y después del primero se corta el flujo.

Asegúrate que todos los flujos estén declarados dentro del array de flujo

**Comment by evmota21** [comment]
> > Mismo error para mí, dentro de un flujo hijo o nieto, coloco 2 captures y después del primero se corta el flujo.
> 
> Asegúrate que todos los flujos estén declarados dentro del array de flujo

Te refieres al array del flujo del padre o del hijo o cuando se declara createFlow al inicio?

**Comment by leifermendez** [comment]
Hola @evmota21 te recomiendo cambiar la logica de flujos hijos a `gotoFlow` es mas mantenible https://647cec9b1899ac660f95a75c--bot-whatsapp.netlify.app/docs/goto-flow/

**Comment by evmota21** [comment]
Hola @leifermendez  :), perfecto, déjame actualizo mi proyecto y me reporto con avances.

Por cierto, un poco off topic: pero existe la manera de probar nuestros desarrollos con un solo número de Whatsapp? A veces quiero probar nuevos detalles pero solamente puedo hacerlo con 2 teléfonos (en el futuro conseguiré un 2ndo teléfono ya de cajón).

**Comment by evmota21** [comment]
Update: resolví este comportamiento poniéndole al flowDynamic("Mensaje", { callback: false }). No sé qué tan elegante es esto, pero me funcionó
