### ISSUE TITLE
[🐛] No inicia la session con el QR

### ISSUE THREAD

**Issue by DanielGauna15** [codigoencasa/bot-whatsapp#771]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Otro

### Describe tu problema

Intento escanear el QR con el proveedor BAILEYS y me sale que esta guardando la SESSION pero luego me dice que el dispositivo se quedo sin conexión.
En la carpeta BOT_SESSION se crea las credenciales pero en la app de WhatsApp nunca se conecto.

### Reproducir error

No se pudo inician sesión. Revisa la conexión a Internet de Tu teléfono y escanea el código QR de nuevo.

### Información Adicional

En el portal web no muestra el QR, tengo que escanearlo abriendo la imagen.png y esta hospedado en REPL.IT

**Comment by leifermendez** [comment]
Debes actualizar tu archivo `package.json`  con estas nuevas dependencias. 

```
      .....
      "@adiwajshing/baileys": "github:WhiskeySockets/Baileys",
      "@adiwajshing/keyed-db": "^0.2.4",
      ......
```

Luego guardas el archivo y ejecutas `npm install` tambien asegurate de borrar la carpeta `bot_sessions`

**Comment by DanielGauna15** [comment]
> 

En la pc lo actualice y funciona.
Pero solo en la pagina hace eso.
Cuando intento crear un nuevo proyecto muchas dependencias en la carpeta de node_modules no las termina instalar aunque ejecute el "npm install" varias veces.

**Comment by ciberfriends** [comment]
> Debes actualizar tu archivo `package.json` con estas nuevas dependencias.
> 
> ```
>       .....
>       "@adiwajshing/baileys": "github:WhiskeySockets/Baileys",
>       "@adiwajshing/keyed-db": "^0.2.4",
>       ......
> ```
> 
> Luego guardas el archivo y ejecutas `npm install` tambien asegurate de borrar la carpeta `bot_sessions`

funciono perfecto con eso justo lo habia encontrado tambien en el discord muchas gracias Leifer
