### ISSUE TITLE
[🐛] flowDynamic retorna al answer

### ISSUE THREAD

**Issue by fensefernando** [codigoencasa/bot-whatsapp#785]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

Saludos.

En algunas ocaciones al ejecutar flowDynamic nuevamente retorna el mensaje de addAnswer

const flowPrincipal = addKeyword(['codigo','a','x'])
    .addAnswer('Ingrese ticket',{capture:true}, async(ctx,{flowDynamic,endFlow})=>{
        const codigo=ctx.body;
        referencia=codigo;
        const data=await consultaAPI(codigo.toUpperCase())
        if(data.error==='ninguno'){
            let actividades=data.actividadViewList.map(actividad=>(`Artiículo: *${actividad.actNombre}* Cantidad: *${actividad.cantidad}*`));
            flowDynamic([{body:[`Establecimiento: *${data.establecimiento}*`,`Cliente: *${data.cliente}*`,actividades].join('\n')},{delay:1000}]);
        }else{
            return endFlow({body:data.error})
        }
    }).addAnswer(['¿Desea registrar este código?  SI / NO',referencia],{capture:true,delay:1000},(ctx,{endFlow})=>{
        if(ctx.body.toUpperCase()==='SI'||ctx.body==='Sí'||ctx.body==='SÍ'){
            console.log(referencia);
            console.log(ctx.body);    
            return endFlow({body:'Registrado'},{delay:1000})
        }else{
            return endFlow({body:'Fin'},{delay:1000})
        }
    })

Este es mi codigo, está con delays para probar alguna diferencia, pero sigue sucediendo igual.

Ojalá sea un error de programación de mi parte.

Saludos.!!!

**Comment by Fabiobonato07** [comment]
Basándome en el código y la descripción que proporcionaste, no estoy completamente seguro de cuál es el problema específico que estás encontrando. Sin embargo, hay algunas cosas que podrías considerar:

	1.	Manejo de errores en la consulta API: Podría ser que tu función consultaAPI(codigo.toUpperCase()) está lanzando un error que no estás capturando. Podrías agregar un bloque try/catch alrededor de esta llamada para manejar los errores potenciales.
	2.	Variables no definidas: Veo que estás usando la variable referencia sin haberla definido previamente en tu código. Asegúrate de que esta variable está correctamente definida e inicializada antes de usarla.
	3.	Errores de formato de cadena: En esta línea de código, parece que tienes algunos problemas con el formato de tu cadena:

let actividades=data.actividadViewList.map(actividad=>(Artiículo: *${actividad.actNombre}* Cantidad: *${actividad.cantidad}*));

Debería verse así:

let actividades=data.actividadViewList.map(actividad=>(`Artículo: *${actividad.actNombre}* Cantidad: *${actividad.cantidad}*`));

Observa las comillas invertidas que engloban la cadena.

Por último, para poder ayudarte de manera más efectiva, necesitaría más detalles sobre el error exacto que estás obteniendo, incluyendo cualquier mensaje de error y el comportamiento exacto que estás observando. Te recomendaría también revisar las bibliotecas o módulos que estás utilizando para asegurarte de que estás siguiendo sus convenciones y prácticas recomendadas.
