### ISSUE TITLE
[🐛] - Error al levantar la aplicación - Balley/MySQL

### ISSUE THREAD

**Issue by AntonioHReyes** [codigoencasa/bot-whatsapp#798]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Otro

### Describe tu problema

Hoy quise desplegar un cambio y Railway fallo con el siguiente mensaje de error

`node:internal/modules/cjs/loader:1080
﻿throw err;
﻿^
﻿Error: Cannot find module '@whiskeysockets/baileys'
﻿Require stack:
﻿- /app/node_modules/@bot-whatsapp/provider/lib/baileys/index.cjs
﻿- /app/app.js
﻿at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
﻿at Module._load (node:internal/modules/cjs/loader:922:27)
﻿at Module.require (node:internal/modules/cjs/loader:1143:19)
﻿at require (node:internal/modules/cjs/helpers:110:18)
﻿at Object.<anonymous> (/app/node_modules/@bot-whatsapp/provider/lib/baileys/index.cjs:15:18)
﻿at Module._compile (node:internal/modules/cjs/loader:1256:14)
﻿at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
﻿at Module.load (node:internal/modules/cjs/loader:1119:32)
﻿at Module._load (node:internal/modules/cjs/loader:960:12)
﻿at Module.require (node:internal/modules/cjs/loader:1143:19) {
﻿code: 'MODULE_NOT_FOUND',
﻿requireStack: [
﻿'/app/node_modules/@bot-whatsapp/provider/lib/baileys/index.cjs',
﻿'/app/app.js'
﻿]
﻿}
﻿Node.js v18.17.0`
﻿
﻿Intente replicar el error en local utilizando la versión de node 18.17.0 y con la ultima versión la 0.1.30 y obtuve el mismo error en local al hacer un npm start, con la versión 0.1.29 no parece haber error, por ahora realizare un downgrade pero seria bueno que lo revisen.

**Comment by andresayac** [comment]
Realiza los siguiente en el mismo orden debería solucionar el inconveniente 

```
npm uninstall @adiwajshing/baileys
npm uninstall @adiwajshing/keyed-db
npm i @whiskeysockets/baileys

```

**Comment by AntonioHReyes** [comment]
@andresayac @leifermendez Siento mucho la tardanza en responder, pero justo hoy me libere un poco y probe lo que me comentan, en mi código no tengo ninguna referencia a baileys directamente por lo cual en cambiar el require no es la solución.

Realize por otro lado los pasos que me comparten y aún asi no pude levantarlo de hecho me borro algunas lineas les muestro

Mis dependencias previo a hacer la secuencia de npm, cabe destacar que tuve que quemar 0.1.29 como comente al principio porque en la ultima versión estaba fallando y fue la unica solución que encontre en ese momento.

```json
"dependencies": {
        "@adiwajshing/baileys": "github:WhiskeySockets/Baileys",
        "@adiwajshing/keyed-db": "^0.2.4",
        "@bot-whatsapp/bot": "0.1.29",
        "@bot-whatsapp/cli": "0.1.29",
        "@bot-whatsapp/database": "0.1.29",
        "@bot-whatsapp/portal": "0.1.29",
        "@bot-whatsapp/provider": "0.1.29",
        "mysql2": "^2.3.3",
        "wa-sticker-formatter": "4.3.2"
    }
``` 

Despues

```json
"dependencies": {
        "@bot-whatsapp/bot": "latest",
        "@bot-whatsapp/cli": "latest",
        "@bot-whatsapp/database": "latest",
        "@bot-whatsapp/portal": "latest",
        "@bot-whatsapp/provider": "latest",
        "@whiskeysockets/baileys": "^6.4.0",
        "mysql2": "^2.3.3",
        "wa-sticker-formatter": "4.3.2"
    }
``` 

El error continua siendo el mismo

node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module '@adiwajshing/baileys'
Require stack:
- /Users/antoniohuertareyes/Documents/personal/chatbots/chat-taelcel/node_modules/@bot-whatsapp/provider/lib/baileys/index.cjs
- /Users/antoniohuertareyes/Documents/personal/chatbots/chat-taelcel/app.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/antoniohuertareyes/Documents/personal/chatbots/chat-taelcel/node_modules/@bot-whatsapp/provider/lib/baileys/index.cjs:15:18)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/antoniohuertareyes/Documents/personal/chatbots/chat-taelcel/node_modules/@bot-whatsapp/provider/lib/baileys/index.cjs',
    '/Users/antoniohuertareyes/Documents/personal/chatbots/chat-taelcel/app.js'
  ]
}

Estoy usando

Node.js v18.17.0

**Comment by andresayac** [comment]
> @andresayac @leifermendez Siento mucho la tardanza en responder, pero justo hoy me libere un poco y probe lo que me comentan, en mi código no tengo ninguna referencia a baileys directamente por lo cual en cambiar el require no es la solución.
> 
> Realize por otro lado los pasos que me comparten y aún asi no pude levantarlo de hecho me borro algunas lineas les muestro
> 
> Mis dependencias previo a hacer la secuencia de npm, cabe destacar que tuve que quemar 0.1.29 como comente al principio porque en la ultima versión estaba fallando y fue la unica solución que encontre en ese momento.
> 
> ```json
> "dependencies": {
>         "@adiwajshing/baileys": "github:WhiskeySockets/Baileys",
>         "@adiwajshing/keyed-db": "^0.2.4",
>         "@bot-whatsapp/bot": "0.1.29",
>         "@bot-whatsapp/cli": "0.1.29",
>         "@bot-whatsapp/database": "0.1.29",
>         "@bot-whatsapp/portal": "0.1.29",
>         "@bot-whatsapp/provider": "0.1.29",
>         "mysql2": "^2.3.3",
>         "wa-sticker-formatter": "4.3.2"
>     }
> ```
> 
> Despues
> 
> ```json
> "dependencies": {
>         "@bot-whatsapp/bot": "latest",
>         "@bot-whatsapp/cli": "latest",
>         "@bot-whatsapp/database": "latest",
>         "@bot-whatsapp/portal": "latest",
>         "@bot-whatsapp/provider": "latest",
>         "@whiskeysockets/baileys": "^6.4.0",
>         "mysql2": "^2.3.3",
>         "wa-sticker-formatter": "4.3.2"
>     }
> ```
> 
> El error continua siendo el mismo
> 
> node:internal/modules/cjs/loader:1080 throw err; ^
> 
> Error: Cannot find module '@adiwajshing/baileys' Require stack:
> 
> * /Users/antoniohuertareyes/Documents/personal/chatbots/chat-taelcel/node_modules/@bot-whatsapp/provider/lib/baileys/index.cjs
> * /Users/antoniohuertareyes/Documents/personal/chatbots/chat-taelcel/app.js
>   at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
>   at Module._load (node:internal/modules/cjs/loader:922:27)
>   at Module.require (node:internal/modules/cjs/loader:1143:19)
>   at require (node:internal/modules/cjs/helpers:110:18)
>   at Object. (/Users/antoniohuertareyes/Documents/personal/chatbots/chat-taelcel/node_modules/@bot-whatsapp/provider/lib/baileys/index.cjs:15:18)
>   at Module._compile (node:internal/modules/cjs/loader:1256:14)
>   at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
>   at Module.load (node:internal/modules/cjs/loader:1119:32)
>   at Module._load (node:internal/modules/cjs/loader:960:12)
>   at Module.require (node:internal/modules/cjs/loader:1143:19) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>   '/Users/antoniohuertareyes/Documents/personal/chatbots/chat-taelcel/node_modules/@bot-whatsapp/provider/lib/baileys/index.cjs',
>   '/Users/antoniohuertareyes/Documents/personal/chatbots/chat-taelcel/app.js'
>   ]
>   }
> 
> Estoy usando
> 
> Node.js v18.17.0

Tengo la sospecha de que esta guardando en cache algo elimina la carpeta node_modules deberia ser suficiente 


npm i -f @bot-whatsapp/bot@latest @bot-whatsapp/cli@latest @bot-whatsapp/database@latest @bot-whatsapp/provider@latest @bot-whatsapp/portal@latest

**Comment by AntonioHReyes** [comment]
con el comando que me pasaste con ese funciono a la perfección por mi parte cierro este issue :3 muchas gracias
