### ISSUE TITLE
Tengo el mismo problema en modo local, tengo la versión mas actual de WhatsApp

### ISSUE THREAD

**Issue by humberni** [codigoencasa/bot-whatsapp#81]
Tengo el mismo problema en modo local, tengo la versión mas actual de WhatsApp

_Originally posted by @humberni in https://github.com/leifermendez/bot-whatsapp/issues/73#issuecomment-1206968969_

**Comment by JaviJam** [comment]
SUcede lo mismo tanto en el terminal como desde el navegador?
