### ISSUE TITLE
[🐛] Como acceder a una imagen

### ISSUE THREAD

**Issue by 3midro** [codigoencasa/bot-whatsapp#857]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Base de datos

### Describe tu problema

Actualmente le solicito al usuario que tome una fotografía de evidencia

.addAnswer(
    'Toma una foto del lugar!',
    {
        capture: true,
    },
    async (ctx, { flowDynamic, state, fallBack }) => {
       console.log(ctx)
       // Validar si el mensaje es una imagen
        if (ctx.message.hasOwnProperty('imageMessage')) {
            const urlImagen = ctx.message.imageMessage.url;
            console.log(urlImagen)
            // Es una imagen
            await flowDynamic('¿Tu imagen es clara y nítida?, recuerda que puedes mejorarla \n*1* Clara y nítida.\n*2* Deseo capturarla nuevamente.')
          
            state.update({ 
                pic: urlImagen
             })
            
            console.log('El mensaje es una imagen');
           
        } else {
            // No es una imagen
            console.log('El mensaje no es una imagen');
            flowDynamic('Tu respuesta no es una imagen, ¡por favor vuelve a capturarla!')
            return fallBack()
        })
        
      el detalle es que debo guardar esa fotografía en una BD, la respuesta me trae una URL y un direct Path, 
      
      message: Message {
    imageMessage: ImageMessage {
      interactiveAnnotations: [],
      scanLengths: [Array],
      **url**: 'https://mmg.whatsapp.net/v/t62.7118-24/30697287_1741094393005354_491261032356478622_n.enc?ccb=11-4&oh=01_AdT_MFoQp7dvt5REU1Mo0s7pKdXHzDvN7e-ZXmGEdDS3gQ&oe=652E7A1F&_nc_sid=000000&mms3=true',
      mimetype: 'image/jpeg',
      **fileSha256**: [Uint8Array],
      fileLength: [Long],
      height: 1599,
      width: 899,
      mediaKey: [Uint8Array],
      **fileEncSha256**: [Uint8Array],
      **directPath**: '/v/t62.7118-24/30697287_1741094393005354_491261032356478622_n.enc?ccb=11-4&oh=01_AdT_MFoQp7dvt5REU1Mo0s7pKdXHzDvN7e-ZXmGEdDS3gQ&oe=652E7A1F&_nc_sid=000000',
      mediaKeyTimestamp: [Long],
      **jpegThumbnail**: [Uint8Array],
      contextInfo: [ContextInfo],
      scansSidecar: [Uint8Array],
      **midQualityFileSha256**: [Uint8Array]
    },
    messageContextInfo: MessageContextInfo {
      deviceListMetadata: [DeviceListMetadata],
      deviceListMetadataVersion: 2
    }  
    
    como puedo acceder a la imagen para enviarsela nuevamente al usuario y confirmar que es la imagen que desea guardar, se que puedo simplemente preguntarle que si desea guardarla, pero quiero hacerle ver cual es la imagen que recibi, de este modo poder enviarla a mySQL

gracias de antemano

**Comment by chelo91** [comment]
Tengo el mismo problema, creo que hay que desencriptarlo, si llego a saber te digo

**Comment by 3midro** [comment]
me pasaron el siguiente codigo, y funcionó!! se los dejo por si es de ayuda para alguien!!

 if (ctx.message.hasOwnProperty('imageMessage')) {
            const myState = state.getMyState()

            try {
                const buffer = await downloadMediaMessage(ctx, "buffer");
                await writeFile(`./sources/img/${myState.id}.jpeg`, buffer);
                await saveAplication();
            } catch (err) {
                console.log(err);
            }

**Comment by chelo91** [comment]
10 puntos, me funciono perfecto, muchas gracias :D
