### ISSUE TITLE
[🐛] Bug cuando se usa addAction

### ISSUE THREAD

**Issue by KichanCrazy** [codigoencasa/bot-whatsapp#865]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

**Al usar varios AddAction (2 o mas) entra en un bucle infinito al usar flowDynamic enviando decenas de mensajes en menos de 5 segundos hasta que se apague el proceso de node.** 

### Información Adicional

**Ejemplo de codigo:**
```javascript
let respuesta
const flujoTest = addKeyword("holahola!")
.addAction( async( ctx, { flowDynamic }) => {
  flowDynamic(`Hola! primer flow dynamic. respondeme algo`)
})
.addAction( { capture: true}, async( ctx, { flowDynamic }) => {
  respuesta = ctx.body
  flowDynamic(`Esto me respondieste ${respuesta}`)
})
.addAction( async( ctx, { flowDynamic }) => {
  flowDynamic(`Hola! segundo flow dynamic. respondeme algo`)
})
.addAction( { capture: true}, async( ctx, { flowDynamic }) => {
  respuesta = ctx.body
  flowDynamic(`Esto me respondieste ${respuesta}`)
})
``` 
**Ejemplo visual en whatsapp:**
![image](https://github.com/codigoencasa/bot-whatsapp/assets/137777472/e2d70ed0-0e79-475c-aceb-9a0624150e73)

**El ejemplo del código es solo para demostrar el bug, parecería obvio que en el ejemplo se puede evitar el bug haciendo uso de _addAnswer_ pero en el uso normal de ese flujo los mensajes son traídos desde una API dependiendo del _state_ del usuario por lo tanto _addAction_ es el método a utilizar en este caso.**

**Comment by Gregoriotecnico** [comment]
alguna solucion a esto?

**Comment by leifermendez** [comment]
Estoy trabjando en esto ;)

**Comment by Gregoriotecnico** [comment]
Yo he comentado esas dos lineas del bundle.bot y ya oarece que no me entre en bucle el tema del flow dynamic. Nose si os servirá de ayuda...

![image](https://github.com/codigoencasa/bot-whatsapp/assets/118696506/d206269a-bbac-4bb4-a625-0ed5db2e39ee)

**Comment by leifermendez** [comment]
Por curiosidad que versión tienes instalada del lib ?

**Comment by Gregoriotecnico** [comment]
![image](https://github.com/codigoencasa/bot-whatsapp/assets/118696506/89fdfaf3-a119-4357-b448-d04bc1664c35)

**Comment by leifermendez** [comment]
@Gregoriotecnico @KichanCrazy  pueden probar esta version `npm install @bot-whatsapp/bot@0.0.174-alpha.0` he puesto tu ejemplo y ya me funcion : https://github.com/codigoencasa/bot-whatsapp/blob/dev/__test__/0.2.0-case.test.js

**Comment by leifermendez** [comment]
Solucionado en la siguiente version 0.1.33

**Comment by savasadar** [comment]
addactions used consecutively do not work.  I have to prepare message with data from db and I am using buttons also so I have to use addaction for customize the answer message, but flow not continue after first addaction.

```
const flowBuy = addKeyword(["buy", "BUY"])
    .addAction(async (ctx, { flowDynamic }) => {
        // preparing buttons...
        await flowDynamic([{ body: "SELECT WALLET", buttons: buttons }])
    })
    .addAction({ capture: true }, async (ctx, { flowDynamic }) => {
        console.log(ctx.body) // fired
        return flowDynamic([{ body: "BUY WITH", buttons: [{ body: "ETH" }, { body: "USDC" }] }])
    })
    .addAction({ capture: true }, async (ctx, { flowDynamic }) => {
        console.log(ctx.body) // not fired
        return flowDynamic([{ body: "BUY AMOUNT", buttons: [{ body: "0.1" }, { body: "0.5" }, { body: "CUSTOM" }] }])
    })
```

**Comment by leifermendez** [comment]
> Hello @leifermendez, addAction used consecutively do not work. I have to prepare message with data from db and I am using buttons also so I have to use addAction for customize the answer message, but flow not continue after first addAction.
> 
> ```
> const flowBuy = addKeyword(["buy", "BUY"])
>     .addAction(async (ctx, { flowDynamic }) => {
>         // preparing buttons...
>         await flowDynamic([{ body: "SELECT WALLET", buttons: buttons }])
>     })
>     .addAction({ capture: true }, async (ctx, { flowDynamic }) => {
>         console.log(ctx.body) // fired
>         return flowDynamic([{ body: "BUY WITH", buttons: [{ body: "ETH" }, { body: "USDC" }] }])
>     })
>     .addAction({ capture: true }, async (ctx, { flowDynamic }) => {
>         console.log(ctx.body) // not fired
>         return flowDynamic([{ body: "BUY AMOUNT", buttons: [{ body: "0.1" }, { body: "0.5" }, { body: "CUSTOM" }] }])
>     })
> ```
> 
> How can I prepare the message as async without using addAction?
> 
> Edit: I think, issue is not about addAction. It is about with flowDynamic. if I use flowDynamic more than 5 flow is not continue. How can I solve this?

Can you try with the last version `0.1.34` https://github.com/codigoencasa/bot-whatsapp/blob/2fe6bd569791f3481183bc9000145f9f48b07673/__test__/0.0.2-case.test.js#L119
