### ISSUE TITLE
[🐛] Error al crear version Docker

### ISSUE THREAD

**Issue by cvc90** [codigoencasa/bot-whatsapp#876]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

Estoy intentando crear el bot a traves de la [guia docker](https://bot-whatsapp.netlify.app/docs/deploy/docker/) y utilizando el [archivo docker](https://github.com/codigoencasa/bot-whatsapp/blob/main/starters/apps/base-wweb-memory/Dockerfile), pero al iniciar el docker una vez creado muestra el siguiente error, al iniciar no encuentra el script "start" como se puede ver en la siguiente imagen.

![image](https://github.com/codigoencasa/bot-whatsapp/assets/76731844/3e7de82c-a523-4bcf-bd69-4053bdb10c6b)

Existe algun paso que me este pasando por alto? o esta opción esta desactualizada?

PD: Ya lo e podido solucionar, el error se debía a que los archivos [app.js](https://github.com/codigoencasa/bot-whatsapp/blob/main/starters/apps/base-wweb-memory/app.js) y [package.json](https://github.com/codigoencasa/bot-whatsapp/blob/main/starters/apps/base-wweb-memory/package.json), no se habían descargado correctamente.

PD2: Como recomendacion podrías actualizar en el [archivo docker](https://github.com/codigoencasa/bot-whatsapp/blob/main/starters/apps/base-wweb-memory/Dockerfile) de node18 a node20? Puedo decir que lo e realizado manualmente el cambio y todo parece funcionar correctamente.

**Comment by leifermendez** [comment]
Excelente @cvc90 seria genial si tu haces esta contribución al proyecto :) así queda registrado bajo tu autoría
