### ISSUE TITLE
Problemas al intentar iniciar sesión con el qr de Heroku 

### ISSUE THREAD

**Issue by Kevinisky27** [codigoencasa/bot-whatsapp#88]
Hola 👋 buen día, he estado intentando utilizar la aplicación del ChatBot, pero me aparece esto
![IMG_2667](https://user-images.githubusercontent.com/60667480/184670409-abe4bbe3-f335-4fe4-944a-7962564667ad.PNG)

**Comment by jose2889** [comment]
@Kevinisky27 activaste la variable MULTI_DEVICE en TRUE  ?

**Comment by Kevinisky27** [comment]
> @Kevinisky27 activaste la variable MULTI_DEVICE en TRUE ?

Si, eso estaba activo
