### ISSUE TITLE
[🐛] Cuando se tiene un flujo con 2 o más AddAnswer que tienen el option { capture: true } no muestra el flujo siguiente, solo la primera respuesta

### ISSUE THREAD

**Issue by zidoxx** [codigoencasa/bot-whatsapp#885]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

Cuando se tiene en un mismo flujo ejemplo flowSi 2 o más .AddAnswer con el parametro option { capture: true }, no avanza con el flujo siguiente, solo muestra el primer mensaje del flow.

    const flowSi = addKeyword('si', 'SI', 'Si')
    .addAnswer('Ingresa tú nombre completo sin errores de ortografia: ', { capture: true},
        async(ctx, { flowDynamic, state }) => {
            await state.update({ name: ctx.body });
            const myState = state.getMyState();
            await flowDynamic(`Bienvenido ${myState.name}`);
        }
    )
    .addAnswer('Ahora ingresa tú numero de documento: ', { capture: true }, 
        async(ctx, { flowDynamic, state })=> {
            await state.update({ document: ctx.body });
            const myState = state.getMyState();
            await flowDynamic(`El numero de documento es: ${myState.document}, es correcto?, escribe *Si* para continuar o *No* para corregir`);
        }, [flowIsCorrect, flowIsNotCorrect]
    )

Tambien se dejo este link en el aparatado de preguntas del Curso de CodigoEnCasa: 
[Playground con ejemplo](https://goldfish-app-4pw93.ondigitalocean.app/workspace/example-padre-hijo-nieto/)

### Reproducir error

Agregar un flujo con 2 .AddAnswer y agregar el parametro option { capture: true }, deberia solo mostrar la primera respuesta.

### Información Adicional

**project base:** base-bailey-memory
**bot-whatsapp version:** 0.1.33
**node version:** V18.18.0
**npm version:** 9.8.1
**O.S:** Windows 10

**Comment by leifermendez** [comment]
#910 puede servirte este issue donde he dejado un comentario con el la implementacion

**Comment by osmaldym** [comment]
A mí me ha sucedido el mismo bug y he instalado todas las nuevas dependencias y no, no funciona

**Comment by jlugolazare2** [comment]
[Cuando se tiene un flujo con 2 o más AddAnswer que tienen el option { capture: true } no muestra el flujo siguiente, solo la primera respuesta](https://github.com/codigoencasa/builderbot/issues/885#top), Tengo el mismo detalle como lo resolviste?
