### ISSUE TITLE
[🐛]change "Twitter" to "𝕏 (Twitter)" in README.md Resources section

### ISSUE THREAD

**Issue by BandhiyaHardik** [codigoencasa/bot-whatsapp#890]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Otro

### Describe tu problema

Before : 
![image](https://github.com/codigoencasa/bot-whatsapp/assets/110784317/4441bd19-9d63-4348-8330-e3a4b1652ec5)

Suggested Change:
![image](https://github.com/codigoencasa/bot-whatsapp/assets/110784317/e59af42f-6fc1-4cb8-a048-9db5e3411081)

**Comment by leifermendez** [comment]
done
