### ISSUE TITLE
ERROR GOTOFLOWS ANIDADOS [🐛]

### ISSUE THREAD

**Issue by Gregoriotecnico** [codigoencasa/bot-whatsapp#910]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

Pasar de un flujo mediante gotoFlow con más de un gotoFlow no funciona (creo que desde que se añadió el tema de la dependencia circular)
El error se vé:
Flujo 1 -> (gotoflow: flujo 2) PERFECTO
Flujo 2  -> (gotoflow: flujo 3) NO LO HACE

Este sistema ya lo tenia yo realizado en bots ateriores funcionando perfectamente. He cambiado la funcion del gotoFlow(interna) de uno de mis bots antiguos hacia este ejemplo y funciona perfectamente.

![image](https://github.com/codigoencasa/bot-whatsapp/assets/118696506/18f24dc5-ef25-4fd0-8b6c-f282a872167e)

**Comment by leifermendez** [comment]
Puedes compartir el ejemplo de los gotoFlows anidados a que te refieres?

**Comment by Gregoriotecnico** [comment]
![IMG-20231109-WA0002_1699604368695](https://github.com/codigoencasa/bot-whatsapp/assets/118696506/982f4236-a651-421b-88c4-bdf6ed45fde3)
Estoy fuera de casa, te mando una captura que tenía de ayer.
Falta el primer flujo que deriva a "flowReserva" (este lo hace bien)
El que hace mal es el que ves en el ejemplo que te adjunto:
Hago gotoFlow hacia "flowReservaNuevoCliente" pero nunca lo hace.

Cuando llegue a casa te envío el otro flujo, pero simpleme te es como si hicieras un gotoFlow desde un events.welcome

**Comment by Gregoriotecnico** [comment]
main.js (Primer gotoFlow que lo hace correctamnte)
`const { addKeyword, addAnswer, EVENTS } = require("@bot-whatsapp/bot");
const cron = require("node-cron");
const { activarDiariamente } = require("./utils/activarDiariamente");
const consultarBlacklist = require("./utils/consultarBlacklist.js");
const conexionSheets = require("./services/conexionSheets.js");
const flowBienvenida = require("./flows/flow.bienvenida.js");
const { flowMenu } = require("./flows/flow.menu.js");
const flowHorario = require("./flows/flow.horario.js");
const flowZona = require("./flows/flow.zona.js");
const flowCarta = require("./flows/flow.carta.js");
const  {flowReserva}  = require("./flows/flow.reserva.js");
let ultimaEjecucionSheet = 0;
let ultimaEjecucionVacaciones = 0;

const flowMain = addKeyword(EVENTS.WELCOME).addAction(async (ctx, ctxFn) => {
  try {
    //TODO - LEEMOS SHEETS PARA LOS MENSAJES
    const tiempoActual = Date.now();
    if (tiempoActual - ultimaEjecucionSheet >= 30000) {
      // Leemos sheets cada 30 segundos
      await conexionSheets(ctxFn);
      ultimaEjecucionSheet = tiempoActual;
    }
    //TODO - LEEMOS MYSQL PARA TRAER ESTADO DEL CHATBOT
    const estadoChatbot = await ctxFn.extensions.mesas.estadoChatbot();
    const consultaConfiguracion =
      await ctxFn.extensions.mesas.consultaConfiguracion();
    ctxFn.extensions.json.escribirEnJson({
      carta: consultaConfiguracion[0].CartaURL,
      mesasExterior: consultaConfiguracion[0].Mesas_exterior,
      mesasInterior: consultaConfiguracion[0].Mesas_Interior,
      personasXmesa: consultaConfiguracion[0].PersonasXmesas
    });
  

    //TODO - INICIAMOS LA DERIVACION A FLUJOS
    const resUsuario = ctx.body.toLowerCase().trim();

    switch (resUsuario) {
     
      case "reserva":
      case "reservar":
      case "reservar mesa":
      case "reserva mesa":
      case "🗓️ *reservar mesa*":
        return ctxFn.gotoFlow(flowReserva);

      default:
        return ctxFn.gotoFlow(flowBienvenida);
    }
  } catch (e) {
    console.log("Error en el flowMain: ", e);
  }
});

module.exports = { flowMain };
`

flow.reserva.js (Estan dos flujos, flowReserva y flowReservaNuevoCliente)
`const { addKeyword, EVENTS, addAction } = require("@bot-whatsapp/bot");
const flowReservaNuevoCliente = require("./subflowreserva");

const flowReserva = addKeyword("__FLOWRESERVA__")
  .addAction(async (ctx, ctxFn) => {
    ctxFn.flowDynamic(ctxFn.extensions.json.leerCampoJson("menuReserva"));
  })
  .addAction(async (ctx, { extensions, gotoFlow }) => {
    const buscarCliente = await extensions.mesas.buscarCliente(
      ctx.from.slice(2)
    );
    if (!buscarCliente) {
      console.log("entra al if");

      return gotoFlow(flowReservaNuevoCliente);
    }
  });

const flowReservaNuevoCliente = addKeyword("12345").addAnswer(
  "Digame su *Nombre y apellidos* para reservar su mesa...",
  { capture: true },
  async (ctx, { state }) => {
    console.log("entro al answer");

    state.update({ Nombre: ctx.body, Telefono: ctx.from.slice(2) });
  }
);

module.exports = { flowReserva, flowReservaNuevoCliente };
`

Evidentemente en el app.js estan implementados los 3 flujos con sus respectivas rutas

**Comment by leifermendez** [comment]
Siguiente release ya esta fixed.

https://github.com/codigoencasa/bot-whatsapp/blob/6edf3730e143c58b3bb36e1d748a6730e6392168/__test__/0.0.2-goto-flow.test.js#L177

**Comment by Elimeleth** [comment]
> Siguiente release ya esta fixed.
> 
> https://github.com/codigoencasa/bot-whatsapp/blob/6edf3730e143c58b3bb36e1d748a6730e6392168/__test__/0.0.2-goto-flow.test.js#L177

Gracias !! casualmente me tope con el mismo issue

un gotoFlow no funciona cuando ya vienes de otro

**Comment by leifermendez** [comment]
> > Siguiente release ya esta fixed.
> > https://github.com/codigoencasa/bot-whatsapp/blob/6edf3730e143c58b3bb36e1d748a6730e6392168/__test__/0.0.2-goto-flow.test.js#L177
> 
> Gracias !! casualmente me tope con el mismo issue
> 
> un gotoFlow no funciona cuando ya vienes de otro

Peudes ir probando con este comando instalas la version que se viene
npm i @bot-whatsapp/bot@dev @bot-whatsapp/cli@dev @bot-whatsapp/database@dev @bot-whatsapp/provider@dev @bot-whatsapp/portal@dev

**Comment by Ariel-Marcelo** [comment]
Disculpen al día de hoy tengo entendido que ese cambio ya esta añadido a la última liberación sin embargo, pruebo el ejemplo que mencionas en bot-whatsapp/__test__/0.0.2-goto-flow.test.js y no entra al addAction del flowReserva, no imprime Flow de la reserva 1 y mucho menos el 2, para verificarlo borre los node_modules e incluso instale las dependencias de desarrollo que mencionas pero sigue pasando lo mismo, por favor pueden indicarme si hay algo que esté haciendo mal. 
![img](https://github.com/codigoencasa/bot-whatsapp/assets/55715664/333d71ea-1957-44cf-8952-dc428ba71803)

**Comment by jhonnymosquera** [comment]
Creo que no se ha solucionado todavia dado que un ejemplo tan siemple como este no funciona

![Captura2](https://github.com/codigoencasa/bot-whatsapp/assets/78888142/1dc67d53-fc7f-44ea-b992-b3d186121163)

![Captura](https://github.com/codigoencasa/bot-whatsapp/assets/78888142/1573f8d4-78e7-4777-aa26-6ec486f9ba13)

**Comment by leifermendez** [comment]
> Creo que no se ha solucionado todavia dado que un ejemplo tan siemple como este no funciona
> 
> ![Captura](https://private-user-images.githubusercontent.com/78888142/307542919-1573f8d4-78e7-4777-aa26-6ec486f9ba13.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4MDEyNzIsIm5iZiI6MTcwODgwMDk3MiwicGF0aCI6Ii83ODg4ODE0Mi8zMDc1NDI5MTktMTU3M2Y4ZDQtNzhlNy00Nzc3LWFhMjYtNmVjNDg2ZjliYTEzLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDE4NTYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3ODIyMDIyYzM4OWUyYjZmN2IyODAxNDFiZjFiYzJmYTNiYTIzYjY1MDM1MmU2MTBhMGNlOTBlNDVjNjg4MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yLIMGjpC7Fk_7UxLKnyMwAgakX-vs9sC9Emep2HuZ1o) ![Captura2](https://private-user-images.githubusercontent.com/78888142/307543028-1dc67d53-fc7f-44ea-b992-b3d186121163.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4MDEyNzIsIm5iZiI6MTcwODgwMDk3MiwicGF0aCI6Ii83ODg4ODE0Mi8zMDc1NDMwMjgtMWRjNjdkNTMtZmM3Zi00NGVhLWI5OTItYjNkMTg2MTIxMTYzLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDE4NTYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhYzgxZGMzMjUwMTJjNzNmM2Y4NzZhMDhhZjUzYzYxYjhhMDcxMzY1MzBkYWM0NzE5NjA4YTI5ZGQ3MjBmYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pxkNU-cFYHRv4nFvIuxSFhj41RoEhlKBHVdOwoU6sz0)

Debes colocar todos los flows en el array de 
```js

createFlow([test_gotoFlow, test_gotoFlow_2, test_gotoFlow_3])

```

**Comment by leifermendez** [comment]
> Disculpen al día de hoy tengo entendido que ese cambio ya esta añadido a la última liberación sin embargo, pruebo el ejemplo que mencionas en bot-whatsapp/**test**/0.0.2-goto-flow.test.js y no entra al addAction del flowReserva, no imprime Flow de la reserva 1 y mucho menos el 2, para verificarlo borre los node_modules e incluso instale las dependencias de desarrollo que mencionas pero sigue pasando lo mismo, por favor pueden indicarme si hay algo que esté haciendo mal. ![img](https://private-user-images.githubusercontent.com/55715664/292538253-333d71ea-1957-44cf-8952-dc428ba71803.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4MDEyNzIsIm5iZiI6MTcwODgwMDk3MiwicGF0aCI6Ii81NTcxNTY2NC8yOTI1MzgyNTMtMzMzZDcxZWEtMTk1Ny00NGNmLTg5NTItZGM0MjhiYTcxODAzLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNFQxODU2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDI0Y2I3NGE5MzJkMGQxNmRkNDcyZDk1MjYwYWVhMzQ1NDNjMmZhNWUwYWJkN2VmNDI0YzdmNjg2MGQxMDIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gO9HbF_rkO3P4rCcNFMBiIySjKblPzdUaA0rNyM9h7I)

Revisa el mensaje del compañero @jhonnymosquera

**Comment by jhonnymosquera** [comment]
@leifermendez Muchas gracias, me gustaria ayudar con la documentasion en el sitio web pero no se como, mientras dejo la solucion mas clara aqui a quien pueda servirle

![solucion1](https://github.com/codigoencasa/bot-whatsapp/assets/78888142/ba9a84da-8f5c-41a5-9906-86b86231ce8b)
![solucion2](https://github.com/codigoencasa/bot-whatsapp/assets/78888142/1bf5f08e-0a76-49cb-ab81-0524f68f186b)

**Comment by leifermendez** [comment]
@jhonnymosquera para evitar el uso de ese uuid usa EVENT.ACTION que tecnicamente hace algo similar con el mismo proposito. ya estamos trabajando en una nueva doc **esta en construccion** pero puedes ir aportando. https://builderbot.vercel.app/methods#goto-flow

**Comment by leifermendez** [comment]
@jhonnymosquera para aporta a la doc debes ir a https://github.com/codigoencasa/documentation  
- hacer Fork del proyecto 
- Luego clonar el proyecto desde tu Fork
- Luego en local instalar dependencias y pnpm run dev
- Luego hacer commit push y pull request
