### ISSUE TITLE
don't support Indonesian language [🐛]

### ISSUE THREAD

**Issue by tukangparkir** [codigoencasa/bot-whatsapp#912]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

This library does not support the Indonesian language. How can it be used for Indonesian language? Please help.

**Comment by ozzyoss77** [comment]
I don't understand what you mean by "it doesn't support the Indonesian language." The library only connects to WhatsApp to generate bots, and any incompatibility with WhatsApp is on the part of the application itself.
