### ISSUE TITLE
[🐛] AddAnswer en Provider META no respeta el orden de los mensajes

### ISSUE THREAD

**Issue by GinnioSarabia** [codigoencasa/bot-whatsapp#919]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

const flowCuenta = addKeyword("cuenta")
  .addAnswer("1")
  .addAnswer("2")
  .addAnswer("3")
  .addAnswer("4")
  .addAnswer("5")
  .addAnswer("6")
  .addAnswer("7")
  .addAnswer("8")
  .addAnswer("9")
  .addAnswer("10");

En Provider META no respeta el orden de los mensajes
![image](https://github.com/codigoencasa/bot-whatsapp/assets/38262734/231ac73c-59d6-479b-973a-99c17aaa47d7)

Si lo hace en PROVIDER Bayles

**Comment by leifermendez** [comment]
Esto ya se encuentra solucionado estará disponible para la siguiente
versión por ahora lo que puedes hacer es colocar el paparemtro delay

**Comment by GinnioSarabia** [comment]
Gracias por la respuesta Leifer

Aproximadamente para cuando crees que se lance la nueva versión?
