### ISSUE TITLE
[🐛]  Despues de usar gotoFlow - sqlMessage: "Column 'refSerialize' cannot be null" 

### ISSUE THREAD

**Issue by gslec** [codigoencasa/bot-whatsapp#920]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

Provider: META

![image](https://github.com/codigoencasa/bot-whatsapp/assets/38262734/f3c020d6-e4c1-4249-9a77-144b19514dfb)

No se obtiene respuesta del flujoHombre o flujoMujer

Y se obtiene este error en consola:

![image](https://github.com/codigoencasa/bot-whatsapp/assets/38262734/c80c3dfb-3835-4e66-8f05-8a6807d3dab8)

Pregunta: 
¿Qué es el campo refSerialize?

¿Solo cambio en la base de datos(Uso Mysql) que permita NULL?

**Comment by jorgechavarriaga** [comment]
@GinnioSarabia me puedes contactar por DM en Discord ? Tengo identificado el error donde se produce y tengo lista la solucion, pero necesito hacer un par de pruebas y no logro replicar el error.

**Comment by chojuanillo** [comment]
Alguna novedad con esto? Me pasa exactamente lo mismo con gotoFlow, y con bd postgresql

**Comment by leifermendez** [comment]
Esto es simplemente el campo refSerialize en la base de datos decir que
puede ser NULL

**Comment by chojuanillo** [comment]
@leifermendez , muchas gracias. Aprovecho para felicitarte por esta librería y por todo el contenido que proporcionas a la comunidad.

**Comment by chojuanillo** [comment]
> ¿Alguna novedad sobre esta ISSUE?

No. Marcas el campo como que puede ser NULL y no da error. Pero lo logico es que hubiera una correción en el codigo para que la creación de la tabla ya marcara este campo para que pueda ser NULL.
