### ISSUE TITLE
EVENTS.WELCOME deja de activar el bot en algunas ocasiones 

### ISSUE THREAD

**Issue by ozzyoss77** [codigoencasa/bot-whatsapp#930]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

Algunas veces (no muy seguido) EVENTS.WELCOME deja de funcionar, el problema esta en el provider de Meta, en otros providers no me paso.

La persona escribe, el mensaje llega a Chatwoot pero el bot no responde.

Aparentemente el tiempo de inactividad del bot es un factor contribuyente.

**Comment by leifermendez** [comment]
que version del bot ?

**Comment by ozzyoss77** [comment]
En todas esta el mismo bug, desde la 1.28 hasta la 1.35
