### ISSUE TITLE
[🐛] Ejecución doble usando AddAction con idle y capture

### ISSUE THREAD

**Issue by diegozz4** [codigoencasa/bot-whatsapp#935]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

DialogFlow

### Describe tu problema

Cuando se emplea addAction con las propiedades idle y capture, el evento se produce en dos ocasiones. Si el tiempo de espera de idle se cumple antes de realizar una escritura, la acción se ejecuta de manera adecuada; sin embargo, si se efectúa una escritura antes de que transcurra dicho tiempo, la acción se ejecuta en duplicado, este es el fragmento de código:

```js
addKeyword([EVENTS.WELCOME]).addAction({ delay: 300 }, (ctx: any, { flowDynamic }: any) => {
   return flowDynamic('Gretting text')
}).addAction({ idle: 20000, capture: true }, (ctx: any, { gotoFlow, flowDynamic }: any) => {
   // Esta seccción se ejecuta doble 
   let { body, idleFallBack, from } = ctx;
   if (idleFallBack) return await gotoFlow(this.flows.inactivityFlow)
   if (!idleFallBack && body) return await flowDynamic('')
})
```

**Comment by leifermendez** [comment]
Buenas si la tengo presente estoy trabajando en eso

**Comment by AdrMXR** [comment]
Alguna novedad en esta issue? tengo el mismo problema

**Comment by chojuanillo** [comment]
Tengo el mismo problema y es indiferente si se utiliza AddAction o addAnswer, solo incluir el parametro idle, ya provoca el problema.
