### ISSUE TITLE
[🐛] Error cuando pulsas una votacion de una Poll

### ISSUE THREAD

**Issue by Gregoriotecnico** [codigoencasa/bot-whatsapp#937]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

Éste error no aparece siempre.
Cuando pulsas una opcion de una poll da error de pollUpdates undefined.
/app/node_modules/@bot-whatsapp/provider/lib/baileys/index.cjs:491
                            const messageOriginalKey = messageCtx?.update?.pollUpdates[0]?.pollUpdateMessageKey;

![image](https://github.com/codigoencasa/bot-whatsapp/assets/118696506/08fb0469-3949-4b5c-9bc7-e99aea8850f4)

**Comment by Rpeche-pk** [comment]
estuve probando y funciona a través de flujos "hijos"
