### ISSUE TITLE
[🐛]addAnswer con media

### ISSUE THREAD

**Issue by matiaslgarcia** [codigoencasa/bot-whatsapp#950]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

Buenas, tengo este addAnswer lo cual lo tengo de prueba donde hay una imagen en la clave media, (adjunto imagen) 
<img width="706" alt="image" src="https://github.com/codigoencasa/bot-whatsapp/assets/50027854/2a6c1af5-d583-4eb9-9c34-3c2d0e1d9aaf">
Cuando el bot esta ejecutandose y se le habla, tira el siguiente error:
<img width="818" alt="image" src="https://github.com/codigoencasa/bot-whatsapp/assets/50027854/f83a261c-e3dc-47ef-a1b3-8b9d9d4fa48e">

Me di cuenta que comentando ese addAnswer el bot funciona correctamente!

### Información Adicional

` .addAnswer(`prueba`,
        {
            media: 'https://uc921a1d334c58e9fd70396c17b1.previews.dropboxusercontent.com/p/thumb/ACL9ev9xfrCqNL79hdwuqKhc6cTiOyr46esh8oOYFiN3_M4PqztDMOG-OZk7XZBY76ryM5SWV5CtMDnEYDYDAS0M0uVK-T5vZ62buUp0BT_F1ptfRbigUdriFW7Tbf4JYlKiz7GZrlPVQBaH9UxJaI6xtCSxAbhtunk4GicQjqv2drT2TCRFWqmOjGieoLio0DbtA7d_6KCWgws7PARDFB2QbGsgeGUQUGwmwlpHTIO_Iiv7CbWy_rDa7k9TJzPMyyT29G1zy7DQp8dgLCzZ76AMAxIXykZhM3dAuCOViuYwhMrzRiBszaKhtmDGZ9Sy5j4VLNDcnn0ywv6275_Qs3xzaVn--zLl4Qn7EoTj1QaOUj4hIeLB2w9lE-j_z-uUBpY/p.png',
        },
        null
    )`

Error:
`
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
`

**Comment by ozzyoss77** [comment]
Se verificó que es un bug, se agendará el fix para una siguiente versión.
@leifermendez el fix será enviado en unos días.
