### ISSUE TITLE
[🐬] Como puedo vaciar y limpiar el historial, para que tome a cada usuario como usuario nuevo

### ISSUE THREAD

**Issue by devmilitia** [codigoencasa/bot-whatsapp#956]
### ¿Cual proveedor usaste?

bailey

### ¿Cual base de datos usaste?

memory

### Conclusion de la prueba

muy buena

### Describe tu caso

[🐬] Como puedo vaciar y limpiar el historial, para que tome a cada usuario como usuario nuevo

### ¿Quieres que te mencionemos?

devmilitia

**Comment by ozzyoss77** [comment]
@devmilitia imagino que hablas del state.
El parámetro state tiene la función clear(), que limpia el state y borra todo lo almacenado.

```js
async (ctx, {state}) => {
    await state.clear()
    return endFlow()
}
```
