### ISSUE TITLE
[🐛] ¿Hay alguna forma de enviar un mensaje llamando a una función?

### ISSUE THREAD

**Issue by Pablussss** [codigoencasa/bot-whatsapp#970]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

Deseo enviar un mensaje a un usuario determinando su número de teléfono sin que el mismo inicie la conversación. Por ejemplo llamando a la función sendMessage(numTelefono, msg), se debe enviar el mensaje de la variable msg al numero de telefono numTelefono. ¿Existe esta opción?

**Comment by leifermendez** [comment]
Si:
https://github.com/codigoencasa/bot-whatsapp/discussions/774
