### ISSUE TITLE
[🐛]Pequeño typo en archivo Readme

### ISSUE THREAD

**Issue by EduardoBautistaDev** [codigoencasa/bot-whatsapp#990]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Otro

### Describe tu problema

Estoy empezando a contribuir en open source y encontré este pequeño error ortográfico:

La palabra "instalación"  en el bullet list al final del README no tiene el acento en la "o".

-----
Entiende más a fondo sus funcionalidades explicadas en nuestra documentación.

- **Instalacion**
- Base de datos
- Proveedores

**Comment by leifermendez** [comment]
Puedes tu mismo modificarlo y así queda con tu autoría
